"""initial_stora

Revision ID: 1cf4c5945a49
Revises: 
Create Date: 2026-06-17 15:56:17.356340

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '1cf4c5945a49'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('capabilities',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('codename', sa.String(length=100), nullable=True),
    sa.Column('name', sa.String(length=100), nullable=True),
    sa.Column('description', sa.String(length=255), nullable=True),
    sa.Column('module', sa.String(length=50), nullable=True),
    sa.Column('created_at', sa.String(length=255), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('codename')
    )
    with op.batch_alter_table('capabilities', schema=None) as batch_op:
        batch_op.create_index('idx_capabilities_codename', ['codename'], unique=True)

    op.create_table('file_fingerprints',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('hash', sa.String(length=64), nullable=True),
    sa.Column('file_size', sa.BigInteger(), nullable=True),
    sa.Column('mime_type', sa.String(length=100), nullable=True),
    sa.Column('storage_path', sa.String(length=500), nullable=True),
    sa.Column('reference_count', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.String(length=255), nullable=True),
    sa.Column('updated_at', sa.String(length=255), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('hash')
    )
    with op.batch_alter_table('file_fingerprints', schema=None) as batch_op:
        batch_op.create_index('idx_file_fingerprints_hash', ['hash'], unique=True)

    op.create_table('roles',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('name', sa.String(length=100), nullable=True),
    sa.Column('slug', sa.String(length=100), nullable=True),
    sa.Column('description', sa.String(length=255), nullable=True),
    sa.Column('is_system', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.String(length=255), nullable=True),
    sa.Column('updated_at', sa.String(length=255), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('slug')
    )
    with op.batch_alter_table('roles', schema=None) as batch_op:
        batch_op.create_index('idx_roles_slug', ['slug'], unique=True)

    op.create_table('sensitive_words',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('word', sa.String(length=200), nullable=True),
    sa.Column('replacement', sa.String(length=200), nullable=True),
    sa.Column('level', sa.Integer(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.String(length=255), nullable=True),
    sa.Column('updated_at', sa.String(length=255), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('sensitive_words', schema=None) as batch_op:
        batch_op.create_index('idx_sensitive_words_word', ['word'], unique=True)

    op.create_table('system_settings',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('setting_key', sa.String(length=100), nullable=True),
    sa.Column('setting_value', sa.Text(), nullable=False),
    sa.Column('setting_type', sa.String(length=255), nullable=True),
    sa.Column('description', sa.String(length=255), nullable=True),
    sa.Column('is_public', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.String(length=255), nullable=True),
    sa.Column('updated_at', sa.String(length=255), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('upload_chunks',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('upload_id', sa.String(length=36), nullable=True),
    sa.Column('chunk_index', sa.Integer(), nullable=True),
    sa.Column('chunk_hash', sa.String(length=64), nullable=True),
    sa.Column('chunk_size', sa.Integer(), nullable=True),
    sa.Column('chunk_path', sa.String(length=500), nullable=True),
    sa.Column('created_at', sa.String(length=255), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('upload_tasks',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('user_id', sa.BigInteger(), nullable=True),
    sa.Column('filename', sa.String(length=255), nullable=True),
    sa.Column('total_size', sa.BigInteger(), nullable=True),
    sa.Column('total_chunks', sa.Integer(), nullable=True),
    sa.Column('uploaded_chunks', sa.Integer(), nullable=True),
    sa.Column('file_hash', sa.String(length=64), nullable=True),
    sa.Column('status', sa.String(length=255), nullable=True),
    sa.Column('created_at', sa.String(length=255), nullable=True),
    sa.Column('updated_at', sa.String(length=255), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('users',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('username', sa.String(length=255), nullable=True),
    sa.Column('email', sa.String(length=255), nullable=True),
    sa.Column('password', sa.String(length=255), nullable=True),
    sa.Column('profile_picture', sa.String(length=255), nullable=True),
    sa.Column('bio', sa.String(length=255), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.Column('is_superuser', sa.Boolean(), nullable=True),
    sa.Column('is_staff', sa.Boolean(), nullable=True),
    sa.Column('date_joined', sa.String(length=255), nullable=True),
    sa.Column('last_login_at', sa.String(length=255), nullable=True),
    sa.Column('last_login_ip', sa.String(length=255), nullable=True),
    sa.Column('register_ip', sa.String(length=255), nullable=True),
    sa.Column('locale', sa.String(length=255), nullable=True),
    sa.Column('is_2fa_enabled', sa.Boolean(), nullable=True),
    sa.Column('totp_secret', sa.String(length=32), nullable=True),
    sa.Column('backup_codes', sa.Text(), nullable=True),
    sa.Column('total_storage', sa.BigInteger(), nullable=True),
    sa.Column('used_storage', sa.BigInteger(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('username')
    )
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.create_index('idx_users_email', ['email'], unique=True)
        batch_op.create_index('idx_users_is_active', ['is_active'], unique=False)
        batch_op.create_index('idx_users_username', ['username'], unique=True)

    op.create_table('audit_logs',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('user_id', sa.BigInteger(), nullable=True),
    sa.Column('user_name', sa.String(length=100), nullable=True),
    sa.Column('level', sa.String(length=20), nullable=True),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('action', sa.String(length=100), nullable=True),
    sa.Column('resource_type', sa.String(length=50), nullable=True),
    sa.Column('resource_id', sa.BigInteger(), nullable=True),
    sa.Column('ip_address', sa.String(length=45), nullable=True),
    sa.Column('user_agent', sa.Text(), nullable=True),
    sa.Column('request_data', sa.Text(), nullable=True),
    sa.Column('status', sa.String(length=20), nullable=True),
    sa.Column('error_message', sa.Text(), nullable=True),
    sa.Column('created_at', sa.String(length=255), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('audit_logs', schema=None) as batch_op:
        batch_op.create_index('idx_audit_logs_action', ['action'], unique=False)
        batch_op.create_index('idx_audit_logs_created_at', ['created_at'], unique=False)
        batch_op.create_index('idx_audit_logs_resource', ['resource_type', 'resource_id'], unique=False)
        batch_op.create_index('idx_audit_logs_user_id', ['user_id'], unique=False)

    op.create_table('field_permissions',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('role_id', sa.BigInteger(), nullable=True),
    sa.Column('model_name', sa.String(length=100), nullable=True),
    sa.Column('field_name', sa.String(length=100), nullable=True),
    sa.Column('can_read', sa.Boolean(), nullable=True),
    sa.Column('can_write', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.String(length=255), nullable=True),
    sa.ForeignKeyConstraint(['role_id'], ['roles.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('file_tags',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('user_id', sa.BigInteger(), nullable=True),
    sa.Column('name', sa.String(length=50), nullable=True),
    sa.Column('color', sa.String(length=10), nullable=True),
    sa.Column('created_at', sa.String(length=255), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('file_tags', schema=None) as batch_op:
        batch_op.create_index('idx_file_tags_user', ['user_id'], unique=False)
        batch_op.create_index('idx_file_tags_user_name', ['user_id', 'name'], unique=True)

    op.create_table('folders',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('user_id', sa.BigInteger(), nullable=True),
    sa.Column('parent_id', sa.BigInteger(), nullable=True),
    sa.Column('name', sa.String(length=255), nullable=True),
    sa.Column('description', sa.String(length=255), nullable=True),
    sa.Column('color', sa.String(length=10), nullable=True),
    sa.Column('icon', sa.String(length=50), nullable=True),
    sa.Column('is_shared', sa.Boolean(), nullable=True),
    sa.Column('sort_order', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.String(length=255), nullable=True),
    sa.Column('updated_at', sa.String(length=255), nullable=True),
    sa.ForeignKeyConstraint(['parent_id'], ['folders.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('folders', schema=None) as batch_op:
        batch_op.create_index('idx_folders_parent', ['parent_id'], unique=False)
        batch_op.create_index('idx_folders_user', ['user_id'], unique=False)
        batch_op.create_index('idx_folders_user_name', ['user_id', 'parent_id', 'name'], unique=True)
        batch_op.create_index('idx_folders_user_parent', ['user_id', 'parent_id'], unique=False)

    op.create_table('gdpr_consents',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('user_id', sa.BigInteger(), nullable=True),
    sa.Column('consent_type', sa.String(length=100), nullable=True),
    sa.Column('granted', sa.Boolean(), nullable=True),
    sa.Column('ip_address', sa.String(length=45), nullable=True),
    sa.Column('created_at', sa.String(length=255), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('gdpr_consents', schema=None) as batch_op:
        batch_op.create_index('idx_gdpr_consents_user', ['user_id'], unique=False)

    op.create_table('login_attempts',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('user_id', sa.BigInteger(), nullable=True),
    sa.Column('username', sa.String(length=255), nullable=True),
    sa.Column('ip_address', sa.String(length=45), nullable=True),
    sa.Column('user_agent', sa.Text(), nullable=True),
    sa.Column('success', sa.Boolean(), nullable=True),
    sa.Column('failure_reason', sa.String(length=255), nullable=True),
    sa.Column('created_at', sa.String(length=255), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('login_attempts', schema=None) as batch_op:
        batch_op.create_index('idx_login_attempts_created', ['created_at'], unique=False)
        batch_op.create_index('idx_login_attempts_ip', ['ip_address'], unique=False)
        batch_op.create_index('idx_login_attempts_user', ['user_id'], unique=False)

    op.create_table('notifications',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('recipient', sa.BigInteger(), nullable=True),
    sa.Column('type', sa.String(length=100), nullable=True),
    sa.Column('title', sa.String(length=200), nullable=True),
    sa.Column('message', sa.Text(), nullable=False),
    sa.Column('is_read', sa.Boolean(), nullable=True),
    sa.Column('read_at', sa.String(length=255), nullable=True),
    sa.Column('created_at', sa.String(length=255), nullable=True),
    sa.Column('updated_at', sa.String(length=255), nullable=True),
    sa.ForeignKeyConstraint(['recipient'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('notifications', schema=None) as batch_op:
        batch_op.create_index('idx_notifications_recipient', ['recipient'], unique=False)
        batch_op.create_index('idx_notifications_type', ['type'], unique=False)
        batch_op.create_index('idx_notifications_unread', ['recipient', 'is_read'], unique=False)

    op.create_table('permission_audit_logs',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('user_id', sa.BigInteger(), nullable=True),
    sa.Column('action', sa.String(length=50), nullable=True),
    sa.Column('target_type', sa.String(length=50), nullable=True),
    sa.Column('target_id', sa.BigInteger(), nullable=True),
    sa.Column('details', sa.Text(), nullable=True),
    sa.Column('created_at', sa.String(length=255), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('permission_audit_logs', schema=None) as batch_op:
        batch_op.create_index('idx_perm_audit_action', ['action'], unique=False)
        batch_op.create_index('idx_perm_audit_created', ['created_at'], unique=False)
        batch_op.create_index('idx_perm_audit_user', ['user_id'], unique=False)

    op.create_table('role_capabilities',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('role_id', sa.BigInteger(), nullable=True),
    sa.Column('capability_id', sa.BigInteger(), nullable=True),
    sa.Column('created_at', sa.String(length=255), nullable=True),
    sa.ForeignKeyConstraint(['capability_id'], ['capabilities.id'], ),
    sa.ForeignKeyConstraint(['role_id'], ['roles.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('role_capabilities', schema=None) as batch_op:
        batch_op.create_index('idx_role_capabilities_capability', ['capability_id'], unique=False)
        batch_op.create_index('idx_role_capabilities_role', ['role_id'], unique=False)
        batch_op.create_index('idx_role_capabilities_unique', ['role_id', 'capability_id'], unique=True)

    op.create_table('search_history',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('user_id', sa.BigInteger(), nullable=True),
    sa.Column('keyword', sa.String(length=255), nullable=True),
    sa.Column('results_count', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.String(length=255), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('search_history', schema=None) as batch_op:
        batch_op.create_index('idx_search_history_created', ['created_at'], unique=False)
        batch_op.create_index('idx_search_history_keyword', ['keyword'], unique=False)
        batch_op.create_index('idx_search_history_user', ['user_id'], unique=False)

    op.create_table('storage_quotas',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('user_id', sa.BigInteger(), nullable=True),
    sa.Column('max_storage', sa.BigInteger(), nullable=True),
    sa.Column('used_storage', sa.BigInteger(), nullable=True),
    sa.Column('max_file_size', sa.BigInteger(), nullable=True),
    sa.Column('max_files_count', sa.Integer(), nullable=True),
    sa.Column('files_count', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.String(length=255), nullable=True),
    sa.Column('updated_at', sa.String(length=255), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('storage_quotas', schema=None) as batch_op:
        batch_op.create_index('idx_storage_quotas_user', ['user_id'], unique=True)

    op.create_table('token_blacklist',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('token_jti', sa.String(length=128), nullable=True),
    sa.Column('token_type', sa.String(length=20), nullable=True),
    sa.Column('user_id', sa.BigInteger(), nullable=True),
    sa.Column('expires_at', sa.String(length=255), nullable=True),
    sa.Column('blacklisted_at', sa.String(length=255), nullable=True),
    sa.Column('reason', sa.String(length=255), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('token_blacklist', schema=None) as batch_op:
        batch_op.create_index('idx_token_blacklist_expires', ['expires_at'], unique=False)
        batch_op.create_index('idx_token_blacklist_jti', ['token_jti'], unique=True)

    op.create_table('user_blocks',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('blocker', sa.BigInteger(), nullable=True),
    sa.Column('blocked_user', sa.BigInteger(), nullable=True),
    sa.Column('reason', sa.String(length=500), nullable=True),
    sa.Column('created_at', sa.String(length=255), nullable=True),
    sa.ForeignKeyConstraint(['blocked_user'], ['users.id'], ),
    sa.ForeignKeyConstraint(['blocker'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('user_blocks', schema=None) as batch_op:
        batch_op.create_index('idx_user_blocks_unique', ['blocker', 'blocked_user'], unique=True)

    op.create_table('user_role_assignments',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('user_id', sa.BigInteger(), nullable=True),
    sa.Column('role_id', sa.BigInteger(), nullable=True),
    sa.Column('created_at', sa.String(length=255), nullable=True),
    sa.ForeignKeyConstraint(['role_id'], ['roles.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('user_role_assignments', schema=None) as batch_op:
        batch_op.create_index('idx_user_roles_role', ['role_id'], unique=False)
        batch_op.create_index('idx_user_roles_unique', ['user_id', 'role_id'], unique=True)
        batch_op.create_index('idx_user_roles_user', ['user_id'], unique=False)

    op.create_table('user_sessions',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('user_id', sa.BigInteger(), nullable=True),
    sa.Column('session_token', sa.String(length=512), nullable=True),
    sa.Column('refresh_token', sa.String(length=512), nullable=True),
    sa.Column('ip_address', sa.String(length=45), nullable=True),
    sa.Column('user_agent', sa.Text(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.Column('expires_at', sa.String(length=255), nullable=True),
    sa.Column('created_at', sa.String(length=255), nullable=True),
    sa.Column('updated_at', sa.String(length=255), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('user_sessions', schema=None) as batch_op:
        batch_op.create_index('idx_user_sessions_token', ['session_token'], unique=True)
        batch_op.create_index('idx_user_sessions_user', ['user_id'], unique=False)

    op.create_table('file_items',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('user_id', sa.BigInteger(), nullable=True),
    sa.Column('folder_id', sa.BigInteger(), nullable=True),
    sa.Column('filename', sa.String(length=255), nullable=True),
    sa.Column('original_filename', sa.String(length=255), nullable=True),
    sa.Column('file_path', sa.String(length=500), nullable=True),
    sa.Column('file_url', sa.String(length=500), nullable=True),
    sa.Column('file_size', sa.BigInteger(), nullable=True),
    sa.Column('mime_type', sa.String(length=100), nullable=True),
    sa.Column('file_type', sa.String(length=20), nullable=True),
    sa.Column('storage_driver', sa.String(length=50), nullable=True),
    sa.Column('storage_bucket', sa.String(length=100), nullable=True),
    sa.Column('storage_key', sa.String(length=500), nullable=True),
    sa.Column('file_hash', sa.String(length=64), nullable=True),
    sa.Column('is_folder', sa.Boolean(), nullable=True),
    sa.Column('is_favorite', sa.Boolean(), nullable=True),
    sa.Column('is_encrypted', sa.Boolean(), nullable=True),
    sa.Column('thumbnail_url', sa.String(length=500), nullable=True),
    sa.Column('width', sa.Integer(), nullable=True),
    sa.Column('height', sa.Integer(), nullable=True),
    sa.Column('duration', sa.Integer(), nullable=True),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('download_count', sa.Integer(), nullable=True),
    sa.Column('sort_order', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.String(length=255), nullable=True),
    sa.Column('updated_at', sa.String(length=255), nullable=True),
    sa.Column('deleted_at', sa.String(length=255), nullable=True),
    sa.ForeignKeyConstraint(['folder_id'], ['folders.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('file_items', schema=None) as batch_op:
        batch_op.create_index('idx_file_items_created', ['created_at'], unique=False)
        batch_op.create_index('idx_file_items_deleted', ['deleted_at'], unique=False)
        batch_op.create_index('idx_file_items_favorite', ['user_id', 'is_favorite'], unique=False)
        batch_op.create_index('idx_file_items_file_type', ['file_type'], unique=False)
        batch_op.create_index('idx_file_items_folder', ['folder_id'], unique=False)
        batch_op.create_index('idx_file_items_hash', ['file_hash'], unique=False)
        batch_op.create_index('idx_file_items_user', ['user_id'], unique=False)
        batch_op.create_index('idx_file_items_user_filename', ['user_id', 'filename'], unique=False)
        batch_op.create_index('idx_file_items_user_folder', ['user_id', 'folder_id'], unique=False)

    op.create_table('access_logs',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('file_id', sa.BigInteger(), nullable=True),
    sa.Column('user_id', sa.BigInteger(), nullable=True),
    sa.Column('anonymous_id', sa.String(length=64), nullable=True),
    sa.Column('action', sa.String(length=50), nullable=True),
    sa.Column('ip_address', sa.String(length=45), nullable=True),
    sa.Column('user_agent', sa.Text(), nullable=True),
    sa.Column('referrer', sa.String(length=500), nullable=True),
    sa.Column('duration_ms', sa.Integer(), nullable=True),
    sa.Column('success', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.String(length=255), nullable=True),
    sa.ForeignKeyConstraint(['file_id'], ['file_items.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('access_logs', schema=None) as batch_op:
        batch_op.create_index('idx_access_logs_action', ['action'], unique=False)
        batch_op.create_index('idx_access_logs_created', ['created_at'], unique=False)
        batch_op.create_index('idx_access_logs_file', ['file_id'], unique=False)
        batch_op.create_index('idx_access_logs_user', ['user_id'], unique=False)

    op.create_table('download_tasks',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('user_id', sa.BigInteger(), nullable=True),
    sa.Column('file_id', sa.BigInteger(), nullable=True),
    sa.Column('download_token', sa.String(length=128), nullable=True),
    sa.Column('status', sa.String(length=20), nullable=True),
    sa.Column('progress', sa.Integer(), nullable=True),
    sa.Column('error_message', sa.Text(), nullable=True),
    sa.Column('source_url', sa.String(length=2048), nullable=True),
    sa.Column('total_size', sa.BigInteger(), nullable=True),
    sa.Column('downloaded_size', sa.BigInteger(), nullable=True),
    sa.Column('created_at', sa.String(length=255), nullable=True),
    sa.Column('updated_at', sa.String(length=255), nullable=True),
    sa.Column('completed_at', sa.String(length=255), nullable=True),
    sa.ForeignKeyConstraint(['file_id'], ['file_items.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('download_tasks', schema=None) as batch_op:
        batch_op.create_index('idx_download_tasks_status', ['status'], unique=False)
        batch_op.create_index('idx_download_tasks_user', ['user_id'], unique=False)

    op.create_table('file_optimizations',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('file_id', sa.BigInteger(), nullable=True),
    sa.Column('thumbnail_url', sa.String(length=500), nullable=True),
    sa.Column('preview_url', sa.String(length=500), nullable=True),
    sa.Column('cdn_url', sa.String(length=500), nullable=True),
    sa.Column('sizes_json', sa.Text(), nullable=True),
    sa.Column('optimization_status', sa.String(length=20), nullable=True),
    sa.Column('created_at', sa.String(length=255), nullable=True),
    sa.Column('updated_at', sa.String(length=255), nullable=True),
    sa.ForeignKeyConstraint(['file_id'], ['file_items.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('file_optimizations', schema=None) as batch_op:
        batch_op.create_index('idx_file_optimizations_file', ['file_id'], unique=False)
        batch_op.create_index('idx_file_optimizations_status', ['optimization_status'], unique=False)

    op.create_table('file_shares',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('file_id', sa.BigInteger(), nullable=True),
    sa.Column('folder_id', sa.BigInteger(), nullable=True),
    sa.Column('owner_id', sa.BigInteger(), nullable=True),
    sa.Column('shared_with_id', sa.BigInteger(), nullable=True),
    sa.Column('permission', sa.String(length=20), nullable=True),
    sa.Column('expires_at', sa.String(length=255), nullable=True),
    sa.Column('is_link_share', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.String(length=255), nullable=True),
    sa.Column('updated_at', sa.String(length=255), nullable=True),
    sa.ForeignKeyConstraint(['file_id'], ['file_items.id'], ),
    sa.ForeignKeyConstraint(['folder_id'], ['folders.id'], ),
    sa.ForeignKeyConstraint(['owner_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['shared_with_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('file_shares', schema=None) as batch_op:
        batch_op.create_index('idx_file_shares_expires', ['expires_at'], unique=False)
        batch_op.create_index('idx_file_shares_file', ['file_id'], unique=False)
        batch_op.create_index('idx_file_shares_folder', ['folder_id'], unique=False)
        batch_op.create_index('idx_file_shares_owner', ['owner_id'], unique=False)
        batch_op.create_index('idx_file_shares_shared_with', ['shared_with_id'], unique=False)

    op.create_table('file_tag_assignments',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('file_id', sa.BigInteger(), nullable=True),
    sa.Column('tag_id', sa.BigInteger(), nullable=True),
    sa.Column('created_at', sa.String(length=255), nullable=True),
    sa.ForeignKeyConstraint(['file_id'], ['file_items.id'], ),
    sa.ForeignKeyConstraint(['tag_id'], ['file_tags.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('file_tag_assignments', schema=None) as batch_op:
        batch_op.create_index('idx_file_tag_assignments_file', ['file_id'], unique=False)
        batch_op.create_index('idx_file_tag_assignments_tag', ['tag_id'], unique=False)
        batch_op.create_index('idx_file_tag_assignments_unique', ['file_id', 'tag_id'], unique=True)

    op.create_table('file_versions',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('file_id', sa.BigInteger(), nullable=True),
    sa.Column('user_id', sa.BigInteger(), nullable=True),
    sa.Column('version_number', sa.Integer(), nullable=True),
    sa.Column('file_size', sa.BigInteger(), nullable=True),
    sa.Column('file_hash', sa.String(length=64), nullable=True),
    sa.Column('storage_path', sa.String(length=500), nullable=True),
    sa.Column('change_note', sa.String(length=500), nullable=True),
    sa.Column('created_at', sa.String(length=255), nullable=True),
    sa.ForeignKeyConstraint(['file_id'], ['file_items.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('file_versions', schema=None) as batch_op:
        batch_op.create_index('idx_file_versions_file', ['file_id'], unique=False)
        batch_op.create_index('idx_file_versions_number', ['file_id', 'version_number'], unique=True)

    op.create_table('trash_items',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('user_id', sa.BigInteger(), nullable=True),
    sa.Column('file_id', sa.BigInteger(), nullable=True),
    sa.Column('folder_id', sa.BigInteger(), nullable=True),
    sa.Column('original_path', sa.String(length=1000), nullable=True),
    sa.Column('original_name', sa.String(length=255), nullable=True),
    sa.Column('file_size', sa.BigInteger(), nullable=True),
    sa.Column('deleted_at', sa.String(length=255), nullable=True),
    sa.Column('expires_at', sa.String(length=255), nullable=True),
    sa.ForeignKeyConstraint(['file_id'], ['file_items.id'], ),
    sa.ForeignKeyConstraint(['folder_id'], ['folders.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('trash_items', schema=None) as batch_op:
        batch_op.create_index('idx_trash_items_expires', ['expires_at'], unique=False)
        batch_op.create_index('idx_trash_items_user', ['user_id'], unique=False)

    op.create_table('share_links',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('share_id', sa.BigInteger(), nullable=True),
    sa.Column('file_id', sa.BigInteger(), nullable=True),
    sa.Column('folder_id', sa.BigInteger(), nullable=True),
    sa.Column('user_id', sa.BigInteger(), nullable=True),
    sa.Column('short_code', sa.String(length=32), nullable=True),
    sa.Column('password_hash', sa.String(length=128), nullable=True),
    sa.Column('permission', sa.String(length=20), nullable=True),
    sa.Column('max_downloads', sa.Integer(), nullable=True),
    sa.Column('download_count', sa.Integer(), nullable=True),
    sa.Column('max_views', sa.Integer(), nullable=True),
    sa.Column('view_count', sa.Integer(), nullable=True),
    sa.Column('expires_at', sa.String(length=255), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.String(length=255), nullable=True),
    sa.Column('updated_at', sa.String(length=255), nullable=True),
    sa.ForeignKeyConstraint(['file_id'], ['file_items.id'], ),
    sa.ForeignKeyConstraint(['folder_id'], ['folders.id'], ),
    sa.ForeignKeyConstraint(['share_id'], ['file_shares.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('short_code')
    )
    with op.batch_alter_table('share_links', schema=None) as batch_op:
        batch_op.create_index('idx_share_links_active', ['is_active'], unique=False)
        batch_op.create_index('idx_share_links_code', ['short_code'], unique=True)
        batch_op.create_index('idx_share_links_expires', ['expires_at'], unique=False)
        batch_op.create_index('idx_share_links_user', ['user_id'], unique=False)

    op.create_table('download_tokens',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('token', sa.String(length=128), nullable=True),
    sa.Column('file_id', sa.BigInteger(), nullable=True),
    sa.Column('user_id', sa.BigInteger(), nullable=True),
    sa.Column('share_link_id', sa.BigInteger(), nullable=True),
    sa.Column('ip_address', sa.String(length=45), nullable=True),
    sa.Column('is_used', sa.Boolean(), nullable=True),
    sa.Column('expires_at', sa.String(length=255), nullable=True),
    sa.Column('created_at', sa.String(length=255), nullable=True),
    sa.Column('used_at', sa.String(length=255), nullable=True),
    sa.ForeignKeyConstraint(['file_id'], ['file_items.id'], ),
    sa.ForeignKeyConstraint(['share_link_id'], ['share_links.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('token')
    )
    with op.batch_alter_table('download_tokens', schema=None) as batch_op:
        batch_op.create_index('idx_download_tokens_file', ['file_id'], unique=False)
        batch_op.create_index('idx_download_tokens_token', ['token'], unique=True)
        batch_op.create_index('idx_download_tokens_used', ['is_used'], unique=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('download_tokens', schema=None) as batch_op:
        batch_op.drop_index('idx_download_tokens_used')
        batch_op.drop_index('idx_download_tokens_token')
        batch_op.drop_index('idx_download_tokens_file')

    op.drop_table('download_tokens')
    with op.batch_alter_table('share_links', schema=None) as batch_op:
        batch_op.drop_index('idx_share_links_user')
        batch_op.drop_index('idx_share_links_expires')
        batch_op.drop_index('idx_share_links_code')
        batch_op.drop_index('idx_share_links_active')

    op.drop_table('share_links')
    with op.batch_alter_table('trash_items', schema=None) as batch_op:
        batch_op.drop_index('idx_trash_items_user')
        batch_op.drop_index('idx_trash_items_expires')

    op.drop_table('trash_items')
    with op.batch_alter_table('file_versions', schema=None) as batch_op:
        batch_op.drop_index('idx_file_versions_number')
        batch_op.drop_index('idx_file_versions_file')

    op.drop_table('file_versions')
    with op.batch_alter_table('file_tag_assignments', schema=None) as batch_op:
        batch_op.drop_index('idx_file_tag_assignments_unique')
        batch_op.drop_index('idx_file_tag_assignments_tag')
        batch_op.drop_index('idx_file_tag_assignments_file')

    op.drop_table('file_tag_assignments')
    with op.batch_alter_table('file_shares', schema=None) as batch_op:
        batch_op.drop_index('idx_file_shares_shared_with')
        batch_op.drop_index('idx_file_shares_owner')
        batch_op.drop_index('idx_file_shares_folder')
        batch_op.drop_index('idx_file_shares_file')
        batch_op.drop_index('idx_file_shares_expires')

    op.drop_table('file_shares')
    with op.batch_alter_table('file_optimizations', schema=None) as batch_op:
        batch_op.drop_index('idx_file_optimizations_status')
        batch_op.drop_index('idx_file_optimizations_file')

    op.drop_table('file_optimizations')
    with op.batch_alter_table('download_tasks', schema=None) as batch_op:
        batch_op.drop_index('idx_download_tasks_user')
        batch_op.drop_index('idx_download_tasks_status')

    op.drop_table('download_tasks')
    with op.batch_alter_table('access_logs', schema=None) as batch_op:
        batch_op.drop_index('idx_access_logs_user')
        batch_op.drop_index('idx_access_logs_file')
        batch_op.drop_index('idx_access_logs_created')
        batch_op.drop_index('idx_access_logs_action')

    op.drop_table('access_logs')
    with op.batch_alter_table('file_items', schema=None) as batch_op:
        batch_op.drop_index('idx_file_items_user_folder')
        batch_op.drop_index('idx_file_items_user_filename')
        batch_op.drop_index('idx_file_items_user')
        batch_op.drop_index('idx_file_items_hash')
        batch_op.drop_index('idx_file_items_folder')
        batch_op.drop_index('idx_file_items_file_type')
        batch_op.drop_index('idx_file_items_favorite')
        batch_op.drop_index('idx_file_items_deleted')
        batch_op.drop_index('idx_file_items_created')

    op.drop_table('file_items')
    with op.batch_alter_table('user_sessions', schema=None) as batch_op:
        batch_op.drop_index('idx_user_sessions_user')
        batch_op.drop_index('idx_user_sessions_token')

    op.drop_table('user_sessions')
    with op.batch_alter_table('user_role_assignments', schema=None) as batch_op:
        batch_op.drop_index('idx_user_roles_user')
        batch_op.drop_index('idx_user_roles_unique')
        batch_op.drop_index('idx_user_roles_role')

    op.drop_table('user_role_assignments')
    with op.batch_alter_table('user_blocks', schema=None) as batch_op:
        batch_op.drop_index('idx_user_blocks_unique')

    op.drop_table('user_blocks')
    with op.batch_alter_table('token_blacklist', schema=None) as batch_op:
        batch_op.drop_index('idx_token_blacklist_jti')
        batch_op.drop_index('idx_token_blacklist_expires')

    op.drop_table('token_blacklist')
    with op.batch_alter_table('storage_quotas', schema=None) as batch_op:
        batch_op.drop_index('idx_storage_quotas_user')

    op.drop_table('storage_quotas')
    with op.batch_alter_table('search_history', schema=None) as batch_op:
        batch_op.drop_index('idx_search_history_user')
        batch_op.drop_index('idx_search_history_keyword')
        batch_op.drop_index('idx_search_history_created')

    op.drop_table('search_history')
    with op.batch_alter_table('role_capabilities', schema=None) as batch_op:
        batch_op.drop_index('idx_role_capabilities_unique')
        batch_op.drop_index('idx_role_capabilities_role')
        batch_op.drop_index('idx_role_capabilities_capability')

    op.drop_table('role_capabilities')
    with op.batch_alter_table('permission_audit_logs', schema=None) as batch_op:
        batch_op.drop_index('idx_perm_audit_user')
        batch_op.drop_index('idx_perm_audit_created')
        batch_op.drop_index('idx_perm_audit_action')

    op.drop_table('permission_audit_logs')
    with op.batch_alter_table('notifications', schema=None) as batch_op:
        batch_op.drop_index('idx_notifications_unread')
        batch_op.drop_index('idx_notifications_type')
        batch_op.drop_index('idx_notifications_recipient')

    op.drop_table('notifications')
    with op.batch_alter_table('login_attempts', schema=None) as batch_op:
        batch_op.drop_index('idx_login_attempts_user')
        batch_op.drop_index('idx_login_attempts_ip')
        batch_op.drop_index('idx_login_attempts_created')

    op.drop_table('login_attempts')
    with op.batch_alter_table('gdpr_consents', schema=None) as batch_op:
        batch_op.drop_index('idx_gdpr_consents_user')

    op.drop_table('gdpr_consents')
    with op.batch_alter_table('folders', schema=None) as batch_op:
        batch_op.drop_index('idx_folders_user_parent')
        batch_op.drop_index('idx_folders_user_name')
        batch_op.drop_index('idx_folders_user')
        batch_op.drop_index('idx_folders_parent')

    op.drop_table('folders')
    with op.batch_alter_table('file_tags', schema=None) as batch_op:
        batch_op.drop_index('idx_file_tags_user_name')
        batch_op.drop_index('idx_file_tags_user')

    op.drop_table('file_tags')
    op.drop_table('field_permissions')
    with op.batch_alter_table('audit_logs', schema=None) as batch_op:
        batch_op.drop_index('idx_audit_logs_user_id')
        batch_op.drop_index('idx_audit_logs_resource')
        batch_op.drop_index('idx_audit_logs_created_at')
        batch_op.drop_index('idx_audit_logs_action')

    op.drop_table('audit_logs')
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_index('idx_users_username')
        batch_op.drop_index('idx_users_is_active')
        batch_op.drop_index('idx_users_email')

    op.drop_table('users')
    op.drop_table('upload_tasks')
    op.drop_table('upload_chunks')
    op.drop_table('system_settings')
    with op.batch_alter_table('sensitive_words', schema=None) as batch_op:
        batch_op.drop_index('idx_sensitive_words_word')

    op.drop_table('sensitive_words')
    with op.batch_alter_table('roles', schema=None) as batch_op:
        batch_op.drop_index('idx_roles_slug')

    op.drop_table('roles')
    with op.batch_alter_table('file_fingerprints', schema=None) as batch_op:
        batch_op.drop_index('idx_file_fingerprints_hash')

    op.drop_table('file_fingerprints')
    with op.batch_alter_table('capabilities', schema=None) as batch_op:
        batch_op.drop_index('idx_capabilities_codename')

    op.drop_table('capabilities')
    # ### end Alembic commands ###
