"""fix_date_joined_last_login_to_datetime

Revision ID: d1cb0194c4cc
Revises: d6191a5dc1cb
Create Date: 2026-06-18 11:47:26.367417

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'd1cb0194c4cc'
down_revision: Union[str, Sequence[str], None] = 'd6191a5dc1cb'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
