-- Block-level storage for .Stora sync engine
-- Block size: 4MB (4194304 bytes)

CREATE TABLE IF NOT EXISTS block_store (
    id BIGINT PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    hash VARCHAR(64) UNIQUE NOT NULL,
    size INTEGER NOT NULL DEFAULT 0,
    storage_path TEXT NOT NULL,
    mime_type VARCHAR(100) NULL,
    ref_count INTEGER NOT NULL DEFAULT 1,
    created_at TIMESTAMP NOT NULL DEFAULT now(),
    updated_at TIMESTAMP NOT NULL DEFAULT now()
);

CREATE TABLE IF NOT EXISTS file_blocks (
    id BIGINT PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    file_hash VARCHAR(64) NOT NULL REFERENCES file_fingerprints(hash) ON DELETE CASCADE,
    block_index INTEGER NOT NULL,
    block_hash VARCHAR(64) NOT NULL REFERENCES block_store(hash),
    block_offset BIGINT NOT NULL DEFAULT 0,
    block_size INTEGER NOT NULL DEFAULT 0,
    created_at TIMESTAMP NOT NULL DEFAULT now(),
    UNIQUE(file_hash, block_index)
);

CREATE INDEX IF NOT EXISTS idx_file_blocks_file_hash ON file_blocks(file_hash);
CREATE INDEX IF NOT EXISTS idx_file_blocks_block_hash ON file_blocks(block_hash);
CREATE INDEX IF NOT EXISTS idx_block_store_hash ON block_store(hash);
