-- UPGRADE
CREATE TABLE IF NOT EXISTS share_link_items (
    id BIGINT PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    share_link_id BIGINT NOT NULL REFERENCES share_links(id) ON DELETE CASCADE,
    file_id BIGINT NOT NULL REFERENCES file_items(id) ON DELETE CASCADE,
    created_at TIMESTAMP NOT NULL DEFAULT now()
);
CREATE INDEX IF NOT EXISTS idx_share_link_items_share_link_id ON share_link_items (share_link_id);
CREATE INDEX IF NOT EXISTS idx_share_link_items_file_id ON share_link_items (file_id);
-- DOWNGRADE
DROP INDEX IF EXISTS idx_share_link_items_file_id;
DROP INDEX IF EXISTS idx_share_link_items_share_link_id;
DROP TABLE IF EXISTS share_link_items CASCADE;
