create table schema_version
(
    revision    varchar(64)                         not null
        primary key,
    description text      default ''::text          not null,
    applied_at  timestamp default CURRENT_TIMESTAMP not null
);


create table block_store
(
    created_at   timestamp default now() not null,
    hash         varchar(64)             not null
        unique,
    id           bigint generated by default as identity
        primary key,
    mime_type    varchar(100),
    ref_count    integer   default 1     not null,
    size         integer   default 0     not null,
    storage_path text                    not null,
    updated_at   timestamp default now() not null
);

create table file_fingerprints
(
    created_at      timestamp default now() not null,
    file_size       bigint    default 0     not null,
    hash            varchar(64)             not null
        unique,
    id              bigint generated by default as identity
        primary key,
    mime_type       varchar(255),
    reference_count integer   default 1     not null,
    storage_path    text,
    updated_at      timestamp default now() not null
);


create index idx_file_fingerprints_hash
    on file_fingerprints (hash);

create table roles
(
    created_at  timestamp default now() not null,
    description text,
    id          bigint generated by default as identity
        primary key,
    is_system   boolean   default false not null,
    name        varchar(100)            not null,
    slug        varchar(100)            not null
        unique,
    updated_at  timestamp default now() not null
);


create table sensitive_words
(
    created_at  timestamp default now() not null,
    id          bigint generated by default as identity
        primary key,
    is_active   boolean   default true  not null,
    level       integer   default 1     not null,
    replacement varchar(255),
    updated_at  timestamp default now() not null,
    word        varchar(255)            not null
);


create table system_settings
(
    created_at    timestamp default now() not null,
    description   text,
    id            bigint generated by default as identity
        primary key,
    is_public     boolean   default false not null,
    setting_key   varchar(100)            not null
        unique,
    setting_type  varchar(50),
    setting_value text                    not null,
    updated_at    timestamp default now() not null
);


create table upload_chunks
(
    chunk_hash  varchar(64),
    chunk_index integer   default 0     not null,
    chunk_path  text,
    chunk_size  integer   default 0     not null,
    created_at  timestamp default now() not null,
    id          bigint generated by default as identity
        primary key,
    upload_id   varchar(255)
);


create table users
(
    backup_codes    text,
    bio             text,
    date_joined     timestamp,
    email           varchar(254)
        unique,
    id              bigint generated by default as identity
        primary key,
    is_2fa_enabled  boolean     default false                      not null,
    is_active       boolean     default true                       not null,
    is_staff        boolean     default false                      not null,
    is_superuser    boolean     default false                      not null,
    last_login_at   timestamp,
    last_login_ip   varchar(45),
    locale          varchar(10) default 'zh_CN'::character varying not null,
    password        text,
    profile_picture text,
    register_ip     varchar(45),
    total_storage   bigint      default '10737418240'::bigint      not null,
    totp_secret     text,
    used_storage    bigint      default 0                          not null,
    username        varchar(150)
        unique
);


create index idx_users_username
    on users (username);

create index idx_users_email
    on users (email);

create table file_blocks
(
    block_hash   varchar(64)             not null
        references block_store (hash),
    block_index  integer                 not null,
    block_offset bigint    default 0     not null,
    block_size   integer   default 0     not null,
    created_at   timestamp default now() not null,
    file_hash    varchar(64)             not null
        references file_fingerprints (hash)
            on delete cascade,
    id           bigint generated by default as identity
        primary key
);


create table download_tasks
(
    created_at     timestamp   default now()                        not null,
    filename       varchar(255),
    folder_id      bigint,
    id             bigint generated by default as identity
        primary key,
    manual_retries integer     default 0                            not null,
    progress       integer     default 0                            not null,
    retry_count    integer     default 0                            not null,
    status         varchar(20) default 'pending'::character varying not null,
    updated_at     timestamp   default now()                        not null,
    url            text                                             not null,
    user_id        bigint                                           not null
        references users
            on delete cascade
);

create table upload_tasks
(
    chunk_size       integer     default 0                            not null,
    created_at       timestamp   default now()                        not null,
    file_size        bigint      default 0                            not null,
    filename         varchar(255),
    final_hash       varchar(64),
    first_chunk_hash varchar(64),
    folder_id        varchar(50),
    id               bigint generated by default as identity
        primary key,
    last_chunk_hash  varchar(64),
    mime_type        varchar(255),
    received_chunks  integer     default 0                            not null,
    status           varchar(20) default 'pending'::character varying not null,
    storage_path     text,
    total_chunks     integer     default 0                            not null,
    updated_at       timestamp   default now()                        not null,
    upload_id        varchar(255),
    user_id          bigint                                           not null
        references users
            on delete cascade
);

create index idx_upload_tasks_status_updated_at
    on upload_tasks (status, updated_at);

create table webhooks
(
    created_at timestamp default now() not null,
    events     text                    not null,
    id         bigint generated by default as identity
        primary key,
    is_active  boolean   default true  not null,
    name       varchar(255)            not null,
    updated_at timestamp default now() not null,
    url        varchar(512)            not null,
    user_id    bigint                  not null
        references users
            on delete cascade
);

create table audit_logs
(
    action     varchar(100)            not null,
    created_at timestamp default now() not null,
    detail     text,
    id         bigint generated by default as identity
        primary key,
    ip_address varchar(45),
    resource   text,
    user_id    bigint
                                       references users
                                           on delete set null
);


create table teams
(
    created_at  timestamp default now() not null,
    description text,
    id          bigint generated by default as identity
        primary key,
    name        varchar(255)            not null,
    owner_id    bigint                  not null
        references users
            on delete cascade,
    updated_at  timestamp default now() not null
);


create table user_sessions
(
    created_at timestamp default now() not null,
    expires_at timestamp,
    id         bigint generated by default as identity
        primary key,
    ip_address varchar(45),
    is_active  boolean   default true  not null,
    token      text,
    user_agent text,
    user_id    bigint                  not null
        references users
            on delete cascade
);


create table notifications
(
    body       text                    not null,
    created_at timestamp default now() not null,
    data       text,
    id         bigint generated by default as identity
        primary key,
    is_read    boolean   default false not null,
    title      varchar(255)            not null,
    type       varchar(50)             not null,
    user_id    bigint                  not null
        references users
            on delete cascade
);


create table vaults
(
    created_at    timestamp    default now()                 not null,
    description   text,
    id            bigint generated by default as identity
        primary key,
    name          varchar(255)                               not null,
    password_hash varchar(128) default ''::character varying not null,
    updated_at    timestamp    default now()                 not null,
    user_id       bigint                                     not null
        references users
            on delete cascade
);


create table file_items
(
    category          varchar(255),
    created_at        timestamp   default now()                      not null,
    deleted_at        timestamp,
    description       text,
    download_count    integer     default 0                          not null,
    duration          integer,
    file_hash         varchar(64),
    file_path         text,
    file_size         bigint      default 0                          not null,
    file_type         varchar(50) default 'other'::character varying not null,
    file_url          text,
    filename          varchar(255),
    folder_id         bigint
                                                                     references file_items
                                                                         on delete set null,
    height            integer,
    id                bigint generated by default as identity
        primary key,
    is_encrypted      boolean     default false                      not null,
    is_favorite       boolean     default false                      not null,
    is_folder         boolean     default false                      not null,
    mime_type         varchar(255),
    original_filename varchar(255),
    sort_order        integer     default 0                          not null,
    storage_bucket    text,
    storage_driver    varchar(50) default 'local'::character varying not null,
    storage_key       text,
    thumbnail_url     text,
    updated_at        timestamp   default now()                      not null,
    user_id           bigint                                         not null
        references users
            on delete cascade,
    width             integer
);


create index idx_file_items_user_id_deleted_at
    on file_items (user_id, deleted_at);

create index idx_file_items_user_id_folder_id_deleted_at_is_folder
    on file_items (user_id, folder_id, deleted_at, is_folder);

create index idx_file_items_user_id_file_type_deleted_at
    on file_items (user_id, file_type, deleted_at);

create index idx_file_items_user_id_created_at_deleted_at
    on file_items (user_id desc, created_at desc, deleted_at desc);

create index idx_file_items_user_id_is_favorite_deleted_at
    on file_items (user_id, is_favorite, deleted_at)
    where (is_favorite = true);

create table file_tags
(
    color      varchar(20),
    created_at timestamp default now() not null,
    id         bigint generated by default as identity
        primary key,
    name       varchar(100)            not null,
    user_id    bigint                  not null
        references users
            on delete cascade
);


create table webhook_events
(
    created_at timestamp   default now()                        not null,
    event      varchar(50)                                      not null,
    id         bigint generated by default as identity
        primary key,
    payload    text,
    response   text,
    status     varchar(20) default 'pending'::character varying not null,
    webhook_id bigint                                           not null
        references webhooks
            on delete cascade
);


create table team_members
(
    created_at timestamp   default now()                       not null,
    id         bigint generated by default as identity
        primary key,
    role       varchar(20) default 'member'::character varying not null,
    team_id    bigint                                          not null
        references teams
            on delete cascade,
    user_id    bigint                                          not null
        references users
            on delete cascade
);

create table vault_items
(
    content_type varchar(64)  default 'file'::character varying not null,
    created_at   timestamp    default now()                     not null,
    file_path    text,
    file_size    bigint       default 0                         not null,
    filename     varchar(512) default ''::character varying     not null,
    id           bigint generated by default as identity
        primary key,
    mime_type    varchar(128) default ''::character varying     not null,
    name         varchar(255)                                   not null,
    updated_at   timestamp    default now()                     not null,
    user_id      bigint                                         not null
        references users
            on delete cascade,
    vault_id     bigint                                         not null
        references vaults
            on delete cascade
);


create index idx_vault_items_vault_id_user_id
    on vault_items (vault_id, user_id);

create table file_comments
(
    content    text                    not null,
    created_at timestamp default now() not null,
    file_id    bigint                  not null
        references file_items
            on delete cascade,
    id         bigint generated by default as identity
        primary key,
    updated_at timestamp default now() not null,
    user_id    bigint                  not null
        references users
            on delete cascade
);


create table file_shares
(
    created_at  timestamp   default now()                     not null,
    expires_at  timestamp,
    file_id     bigint                                        not null
        references file_items
            on delete cascade,
    id          bigint generated by default as identity
        primary key,
    owner_id    bigint                                        not null
        references users
            on delete cascade,
    permission  varchar(20) default 'view'::character varying not null,
    shared_with bigint                                        not null
        references users
            on delete cascade
);


create table share_links
(
    created_at     timestamp    default now()                     not null,
    download_count integer      default 0                         not null,
    expires_at     timestamp,
    file_id        bigint
                                                                  references file_items
                                                                      on delete set null,
    folder_id      bigint
                                                                  references file_items
                                                                      on delete set null,
    id             bigint generated by default as identity
        primary key,
    is_active      boolean      default true                      not null,
    max_downloads  integer      default 0                         not null,
    password       varchar(128) default ''::character varying     not null,
    permission     varchar(20)  default 'read'::character varying not null,
    short_code     varchar(32)  default ''::character varying     not null,
    token          varchar(64)  default ''::character varying     not null,
    user_id        bigint                                         not null
        references users
            on delete cascade,
    view_count     integer      default 0                         not null
);


create index idx_share_links_short_code
    on share_links (short_code)
    where ((short_code)::text <> ''::text);

create index idx_share_links_user_id_created_at
    on share_links (user_id desc, created_at desc);

create table transcription_tasks
(
    created_at timestamp   default now()                        not null,
    error_msg  text,
    file_id    bigint                                           not null
        references file_items
            on delete cascade,
    id         bigint generated by default as identity
        primary key,
    progress   integer     default 0                            not null,
    result_url text,
    status     varchar(20) default 'pending'::character varying not null,
    updated_at timestamp   default now()                        not null,
    user_id    bigint                                           not null
        references users
            on delete cascade
);

create table file_versions
(
    created_at     timestamp   default now()                      not null,
    created_by     bigint
        references users,
    file_hash      varchar(64),
    file_id        bigint                                         not null
        references file_items
            on delete cascade,
    file_path      text,
    file_size      bigint      default 0                          not null,
    id             bigint generated by default as identity
        primary key,
    storage_driver varchar(50) default 'local'::character varying not null,
    version_num    integer     default 1                          not null
);

create table team_folders
(
    created_at timestamp   default now()                     not null,
    folder_id  bigint                                        not null
        references file_items
            on delete cascade,
    id         bigint generated by default as identity
        primary key,
    permission varchar(20) default 'read'::character varying not null,
    team_id    bigint                                        not null
        references teams
            on delete cascade
);


create table file_tag_assignments
(
    file_id bigint not null
        references file_items
            on delete cascade,
    id      bigint generated by default as identity
        primary key,
    tag_id  bigint not null
        references file_tags
            on delete cascade
);

create table share_link_items
(
    created_at    timestamp default now() not null,
    file_id       bigint                  not null
        references file_items
            on delete cascade,
    id            bigint generated by default as identity
        primary key,
    share_link_id bigint                  not null
        references share_links
            on delete cascade
);

