-- Migration v5: initial schema from models.yaml
-- Generated from config/models.yaml
-- 2026-06-22T15:12:46+08:00

-- AuditLog: 审计日志
CREATE TABLE IF NOT EXISTS audit_logs (
    action VARCHAR(100) NOT NULL,
    created_at TIMESTAMP NOT NULL DEFAULT now(),
    detail TEXT NOT NULL,
    id BIGINT PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    ip_address VARCHAR(45) NOT NULL,
    resource TEXT NOT NULL,
    user_id BIGINT NOT NULL REFERENCES users(id) ON DELETE SET NULL
);

-- Capability: 权限能力定义
CREATE TABLE IF NOT EXISTS capabilities (
    codename VARCHAR(100) UNIQUE NOT NULL,
    created_at TIMESTAMP NOT NULL DEFAULT now(),
    description TEXT NOT NULL,
    id BIGINT PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    module VARCHAR(100) NOT NULL,
    name VARCHAR(200) NOT NULL
);

-- FileFingerprint: 文件去重指纹
CREATE TABLE IF NOT EXISTS file_fingerprints (
    created_at TIMESTAMP NOT NULL DEFAULT now(),
    file_size BIGINT NOT NULL DEFAULT 0,
    hash VARCHAR(64) UNIQUE NOT NULL,
    id BIGINT PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    mime_type VARCHAR(255) NOT NULL,
    reference_count INTEGER NOT NULL DEFAULT 1,
    storage_path TEXT NOT NULL,
    updated_at TIMESTAMP NOT NULL DEFAULT now()
);
CREATE INDEX IF NOT EXISTS idx_file_fingerprints_hash ON file_fingerprints (hash);

-- FileItem: 文件条目
CREATE TABLE IF NOT EXISTS file_items (
    created_at TIMESTAMP NOT NULL DEFAULT now(),
    deleted_at TIMESTAMP NOT NULL,
    description TEXT NOT NULL,
    download_count INTEGER NOT NULL DEFAULT 0,
    duration INTEGER NOT NULL,
    file_hash VARCHAR(64) NOT NULL,
    file_path TEXT NOT NULL,
    file_size BIGINT NOT NULL DEFAULT 0,
    file_type VARCHAR(50) NOT NULL DEFAULT 'other',
    file_url TEXT NOT NULL,
    filename VARCHAR(255) NOT NULL,
    folder_id BIGINT NOT NULL REFERENCES folders(id) ON DELETE SET NULL,
    height INTEGER NOT NULL,
    id BIGINT PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    is_encrypted BOOLEAN NOT NULL DEFAULT false,
    is_favorite BOOLEAN NOT NULL DEFAULT false,
    is_folder BOOLEAN NOT NULL DEFAULT false,
    mime_type VARCHAR(255) NOT NULL,
    original_filename VARCHAR(255) NOT NULL,
    sort_order INTEGER NOT NULL DEFAULT 0,
    storage_bucket TEXT NOT NULL,
    storage_driver VARCHAR(50) NOT NULL DEFAULT 'local',
    storage_key TEXT NOT NULL,
    thumbnail_url TEXT NOT NULL,
    updated_at TIMESTAMP NOT NULL DEFAULT now(),
    user_id BIGINT NOT NULL REFERENCES users(id) ON DELETE CASCADE,
    width INTEGER NOT NULL
);
CREATE INDEX IF NOT EXISTS idx_file_items_user_id_deleted_at ON file_items (user_id, deleted_at);
CREATE INDEX IF NOT EXISTS idx_file_items_user_id_folder_id_deleted_at ON file_items (user_id, folder_id, deleted_at);
CREATE INDEX IF NOT EXISTS idx_file_items_user_id_file_type_deleted_at ON file_items (user_id, file_type, deleted_at);
CREATE INDEX IF NOT EXISTS idx_file_items_user_id_created_at_deleted_at ON file_items (user_id DESC, created_at DESC, deleted_at DESC);
CREATE INDEX IF NOT EXISTS idx_file_items_user_id_is_favorite_deleted_at ON file_items (user_id, is_favorite, deleted_at) WHERE is_favorite = true;

-- FileShare: 用户间分享
CREATE TABLE IF NOT EXISTS file_shares (
    created_at TIMESTAMP NOT NULL DEFAULT now(),
    expires_at TIMESTAMP NOT NULL,
    file_id BIGINT NOT NULL REFERENCES file_items(id) ON DELETE CASCADE,
    id BIGINT PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    owner_id BIGINT NOT NULL REFERENCES users(id) ON DELETE CASCADE,
    permission VARCHAR(20) NOT NULL DEFAULT 'view',
    shared_with BIGINT NOT NULL REFERENCES users(id) ON DELETE CASCADE
);

-- FileTag: 文件标签
CREATE TABLE IF NOT EXISTS file_tags (
    color VARCHAR(20) NOT NULL,
    created_at TIMESTAMP NOT NULL DEFAULT now(),
    id BIGINT PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    name VARCHAR(100) NOT NULL,
    user_id BIGINT NOT NULL REFERENCES users(id) ON DELETE CASCADE
);

-- FileTagAssignment: 文件-标签关联
CREATE TABLE IF NOT EXISTS file_tag_assignments (
    file_id BIGINT NOT NULL REFERENCES file_items(id) ON DELETE CASCADE,
    id BIGINT PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    tag_id BIGINT NOT NULL REFERENCES file_tags(id) ON DELETE CASCADE
);

-- FileVersion: 文件版本
CREATE TABLE IF NOT EXISTS file_versions (
    created_at TIMESTAMP NOT NULL DEFAULT now(),
    created_by BIGINT NOT NULL REFERENCES users(id),
    file_hash VARCHAR(64) NOT NULL,
    file_id BIGINT NOT NULL REFERENCES file_items(id) ON DELETE CASCADE,
    file_path TEXT NOT NULL,
    file_size BIGINT NOT NULL DEFAULT 0,
    id BIGINT PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    version_num INTEGER NOT NULL DEFAULT 1
);

-- Folder: 文件夹
CREATE TABLE IF NOT EXISTS folders (
    created_at TIMESTAMP NOT NULL DEFAULT now(),
    id BIGINT PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    name VARCHAR(255) NOT NULL,
    parent_id BIGINT NOT NULL REFERENCES folders(id) ON DELETE CASCADE,
    sort_order INTEGER NOT NULL DEFAULT 0,
    updated_at TIMESTAMP NOT NULL DEFAULT now(),
    user_id BIGINT NOT NULL REFERENCES users(id) ON DELETE CASCADE
);
CREATE INDEX IF NOT EXISTS idx_folders_user_id_parent_id ON folders (user_id, parent_id);

-- LoginAttempt: 登录尝试记录（用于暴力破解防护）
CREATE TABLE IF NOT EXISTS login_attempts (
    created_at TIMESTAMP NOT NULL DEFAULT now(),
    id BIGINT PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    ip_address VARCHAR(45) NOT NULL,
    success BOOLEAN NOT NULL DEFAULT false,
    username VARCHAR(150) NOT NULL
);
CREATE INDEX IF NOT EXISTS idx_login_attempts_ip_address_created_at ON login_attempts (ip_address, created_at);
CREATE INDEX IF NOT EXISTS idx_login_attempts_username_created_at ON login_attempts (username, created_at);

-- Notification: 通知
CREATE TABLE IF NOT EXISTS notifications (
    body TEXT NOT NULL,
    created_at TIMESTAMP NOT NULL DEFAULT now(),
    data TEXT NOT NULL,
    id BIGINT PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    is_read BOOLEAN NOT NULL DEFAULT false,
    title VARCHAR(255) NOT NULL,
    type VARCHAR(50) NOT NULL,
    user_id BIGINT NOT NULL REFERENCES users(id) ON DELETE CASCADE
);

-- Role: 角色定义
CREATE TABLE IF NOT EXISTS roles (
    created_at TIMESTAMP NOT NULL DEFAULT now(),
    description TEXT NOT NULL,
    id BIGINT PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    is_system BOOLEAN NOT NULL DEFAULT false,
    name VARCHAR(100) NOT NULL,
    slug VARCHAR(100) UNIQUE NOT NULL,
    updated_at TIMESTAMP NOT NULL DEFAULT now()
);

-- RoleCapability: 角色-权限关联
CREATE TABLE IF NOT EXISTS role_capabilities (
    capability_id BIGINT NOT NULL REFERENCES capabilities(id) ON DELETE CASCADE,
    id BIGINT PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    role_id BIGINT NOT NULL REFERENCES roles(id) ON DELETE CASCADE
);

-- SensitiveWord: 敏感词过滤
CREATE TABLE IF NOT EXISTS sensitive_words (
    created_at TIMESTAMP NOT NULL DEFAULT now(),
    id BIGINT PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    is_active BOOLEAN NOT NULL DEFAULT true,
    level INTEGER NOT NULL DEFAULT 1,
    replacement VARCHAR(255) NOT NULL,
    updated_at TIMESTAMP NOT NULL DEFAULT now(),
    word VARCHAR(255) NOT NULL
);

-- ShareLink: 分享链接
CREATE TABLE IF NOT EXISTS share_links (
    created_at TIMESTAMP NOT NULL DEFAULT now(),
    download_count INTEGER NOT NULL DEFAULT 0,
    expires_at TIMESTAMP NOT NULL,
    file_id BIGINT NOT NULL REFERENCES file_items(id) ON DELETE SET NULL,
    folder_id BIGINT NOT NULL REFERENCES folders(id) ON DELETE SET NULL,
    id BIGINT PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    is_active BOOLEAN NOT NULL DEFAULT true,
    max_downloads INTEGER NOT NULL DEFAULT 0,
    password VARCHAR(128) NOT NULL DEFAULT '',
    permission VARCHAR(20) NOT NULL DEFAULT 'read',
    short_code VARCHAR(32) NOT NULL DEFAULT '',
    token VARCHAR(64) NOT NULL DEFAULT '',
    user_id BIGINT NOT NULL REFERENCES users(id) ON DELETE CASCADE,
    view_count INTEGER NOT NULL DEFAULT 0
);
CREATE INDEX IF NOT EXISTS idx_share_links_short_code ON share_links (short_code) WHERE short_code != '';
CREATE INDEX IF NOT EXISTS idx_share_links_user_id_created_at ON share_links (user_id DESC, created_at DESC);

-- StorageQuota: 存储配额
CREATE TABLE IF NOT EXISTS storage_quotas (
    created_at TIMESTAMP NOT NULL DEFAULT now(),
    id BIGINT PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    total_bytes BIGINT NOT NULL DEFAULT 0,
    updated_at TIMESTAMP NOT NULL DEFAULT now(),
    used_bytes BIGINT NOT NULL DEFAULT 0,
    user_id BIGINT NOT NULL REFERENCES users(id) ON DELETE CASCADE
);

-- SystemSetting: 系统设置（键值对）
CREATE TABLE IF NOT EXISTS system_settings (
    created_at TIMESTAMP NOT NULL DEFAULT now(),
    description TEXT NOT NULL,
    id BIGINT PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    is_public BOOLEAN NOT NULL DEFAULT false,
    setting_key VARCHAR(100) UNIQUE NOT NULL,
    setting_type VARCHAR(50) NOT NULL DEFAULT 'string',
    setting_value TEXT NOT NULL,
    updated_at TIMESTAMP NOT NULL DEFAULT now()
);

-- TokenBlacklist: JWT 黑名单
CREATE TABLE IF NOT EXISTS token_blacklist (
    blacklisted_at TIMESTAMP NOT NULL DEFAULT now(),
    expires_at TIMESTAMP NOT NULL,
    id BIGINT PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    token TEXT NOT NULL
);

-- UploadChunk: 上传分片
CREATE TABLE IF NOT EXISTS upload_chunks (
    chunk_hash VARCHAR(64) NOT NULL,
    chunk_index INTEGER NOT NULL DEFAULT 0,
    chunk_path TEXT NOT NULL,
    chunk_size INTEGER NOT NULL DEFAULT 0,
    created_at TIMESTAMP NOT NULL DEFAULT now(),
    id BIGINT PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    upload_id VARCHAR(255) NOT NULL
);

-- UploadTask: 文件上传任务
CREATE TABLE IF NOT EXISTS upload_tasks (
    chunk_size INTEGER NOT NULL DEFAULT 0,
    created_at TIMESTAMP NOT NULL DEFAULT now(),
    file_size BIGINT NOT NULL DEFAULT 0,
    filename VARCHAR(255) NOT NULL,
    final_hash VARCHAR(64) NOT NULL,
    first_chunk_hash VARCHAR(64) NOT NULL,
    folder_id VARCHAR(50) NOT NULL,
    id BIGINT PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    last_chunk_hash VARCHAR(64) NOT NULL,
    mime_type VARCHAR(255) NOT NULL,
    received_chunks INTEGER NOT NULL DEFAULT 0,
    status VARCHAR(20) NOT NULL DEFAULT 'pending',
    storage_path TEXT NOT NULL,
    total_chunks INTEGER NOT NULL DEFAULT 0,
    updated_at TIMESTAMP NOT NULL DEFAULT now(),
    upload_id VARCHAR(255) NOT NULL,
    user_id BIGINT NOT NULL REFERENCES users(id) ON DELETE CASCADE
);
CREATE INDEX IF NOT EXISTS idx_upload_tasks_status_updated_at ON upload_tasks (status, updated_at);

-- User: 用户账户
CREATE TABLE IF NOT EXISTS users (
    backup_codes TEXT NOT NULL,
    bio TEXT NOT NULL,
    date_joined TIMESTAMP NOT NULL,
    email VARCHAR(254) UNIQUE NOT NULL,
    id BIGINT PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    is_2fa_enabled BOOLEAN NOT NULL DEFAULT false,
    is_active BOOLEAN NOT NULL DEFAULT true,
    is_staff BOOLEAN NOT NULL DEFAULT false,
    is_superuser BOOLEAN NOT NULL DEFAULT false,
    last_login_at TIMESTAMP NOT NULL,
    last_login_ip VARCHAR(45) NOT NULL,
    locale VARCHAR(10) NOT NULL DEFAULT 'zh_CN',
    password TEXT NOT NULL,
    profile_picture TEXT NOT NULL,
    register_ip VARCHAR(45) NOT NULL,
    total_storage BIGINT NOT NULL DEFAULT 1073741824,
    totp_secret TEXT NOT NULL,
    used_storage BIGINT NOT NULL DEFAULT 0,
    username VARCHAR(150) UNIQUE NOT NULL
);
CREATE INDEX IF NOT EXISTS idx_users_username ON users (username);
CREATE INDEX IF NOT EXISTS idx_users_email ON users (email);

-- UserRole: 用户-角色关联
CREATE TABLE IF NOT EXISTS user_roles (
    id BIGINT PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    role_id BIGINT NOT NULL REFERENCES roles(id) ON DELETE CASCADE,
    user_id BIGINT NOT NULL REFERENCES users(id) ON DELETE CASCADE
);

-- UserSession: 用户登录会话
CREATE TABLE IF NOT EXISTS user_sessions (
    created_at TIMESTAMP NOT NULL DEFAULT now(),
    expires_at TIMESTAMP NOT NULL,
    id BIGINT PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    ip_address VARCHAR(45) NOT NULL,
    is_active BOOLEAN NOT NULL DEFAULT true,
    token TEXT NOT NULL,
    user_agent TEXT NOT NULL,
    user_id BIGINT NOT NULL REFERENCES users(id) ON DELETE CASCADE
);

-- Vault: 加密保险箱
CREATE TABLE IF NOT EXISTS vaults (
    created_at TIMESTAMP NOT NULL DEFAULT now(),
    description TEXT NOT NULL,
    id BIGINT PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    name VARCHAR(255) NOT NULL,
    password_hash VARCHAR(128) NOT NULL DEFAULT '',
    updated_at TIMESTAMP NOT NULL DEFAULT now(),
    user_id BIGINT NOT NULL REFERENCES users(id) ON DELETE CASCADE
);

-- VaultItem: 保险箱条目
CREATE TABLE IF NOT EXISTS vault_items (
    content TEXT NOT NULL,
    content_type VARCHAR(64) NOT NULL DEFAULT 'file',
    created_at TIMESTAMP NOT NULL DEFAULT now(),
    file_size BIGINT NOT NULL DEFAULT 0,
    filename VARCHAR(512) NOT NULL DEFAULT '',
    id BIGINT PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    mime_type VARCHAR(128) NOT NULL DEFAULT '',
    name VARCHAR(255) NOT NULL,
    updated_at TIMESTAMP NOT NULL DEFAULT now(),
    user_id BIGINT NOT NULL REFERENCES users(id) ON DELETE CASCADE,
    vault_id BIGINT NOT NULL REFERENCES vaults(id) ON DELETE CASCADE
);
CREATE INDEX IF NOT EXISTS idx_vault_items_vault_id_user_id ON vault_items (vault_id, user_id);

