-- UPGRADE
-- schema_version tracking table
CREATE TABLE IF NOT EXISTS schema_version (
    revision    VARCHAR(64) PRIMARY KEY,
    description TEXT NOT NULL DEFAULT '',
    applied_at  TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP
);

-- Capability: 权限能力定义
CREATE TABLE IF NOT EXISTS capabilities (
    codename VARCHAR(100) UNIQUE NOT NULL,
    created_at TIMESTAMP NOT NULL DEFAULT now(),
    description TEXT NULL,
    id BIGINT PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    module VARCHAR(100) NULL,
    name VARCHAR(200) NULL
);

-- FileFingerprint: 文件去重指纹
CREATE TABLE IF NOT EXISTS file_fingerprints (
    created_at TIMESTAMP NOT NULL DEFAULT now(),
    file_size BIGINT NOT NULL DEFAULT 0,
    hash VARCHAR(64) UNIQUE NOT NULL,
    id BIGINT PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    mime_type VARCHAR(255) NULL,
    reference_count INTEGER NOT NULL DEFAULT 1,
    storage_path TEXT NULL,
    updated_at TIMESTAMP NOT NULL DEFAULT now()
);
CREATE INDEX IF NOT EXISTS idx_file_fingerprints_hash ON file_fingerprints (hash);

-- LoginAttempt: 登录尝试记录（用于暴力破解防护）
CREATE TABLE IF NOT EXISTS login_attempts (
    created_at TIMESTAMP NOT NULL DEFAULT now(),
    id BIGINT PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    ip_address VARCHAR(45) NULL,
    success BOOLEAN NOT NULL DEFAULT false,
    username VARCHAR(150) NULL
);
CREATE INDEX IF NOT EXISTS idx_login_attempts_ip_address_created_at ON login_attempts (ip_address, created_at);
CREATE INDEX IF NOT EXISTS idx_login_attempts_username_created_at ON login_attempts (username, created_at);

-- Role: 角色定义
CREATE TABLE IF NOT EXISTS roles (
    created_at TIMESTAMP NOT NULL DEFAULT now(),
    description TEXT NULL,
    id BIGINT PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    is_system BOOLEAN NOT NULL DEFAULT false,
    name VARCHAR(100) NOT NULL,
    slug VARCHAR(100) UNIQUE NOT NULL,
    updated_at TIMESTAMP NOT NULL DEFAULT now()
);

-- SensitiveWord: 敏感词过滤
CREATE TABLE IF NOT EXISTS sensitive_words (
    created_at TIMESTAMP NOT NULL DEFAULT now(),
    id BIGINT PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    is_active BOOLEAN NOT NULL DEFAULT true,
    level INTEGER NOT NULL DEFAULT 1,
    replacement VARCHAR(255) NULL,
    updated_at TIMESTAMP NOT NULL DEFAULT now(),
    word VARCHAR(255) NOT NULL
);

-- SystemSetting: 系统设置（键值对）
CREATE TABLE IF NOT EXISTS system_settings (
    created_at TIMESTAMP NOT NULL DEFAULT now(),
    description TEXT NULL,
    id BIGINT PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    is_public BOOLEAN NOT NULL DEFAULT false,
    setting_key VARCHAR(100) UNIQUE NOT NULL,
    setting_type VARCHAR(50) NULL DEFAULT 'string',
    setting_value TEXT NOT NULL,
    updated_at TIMESTAMP NOT NULL DEFAULT now()
);

-- TokenBlacklist: JWT 黑名单
CREATE TABLE IF NOT EXISTS token_blacklist (
    blacklisted_at TIMESTAMP NOT NULL DEFAULT now(),
    expires_at TIMESTAMP NULL,
    id BIGINT PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    token TEXT NULL
);

-- UploadChunk: 上传分片
CREATE TABLE IF NOT EXISTS upload_chunks (
    chunk_hash VARCHAR(64) NULL,
    chunk_index INTEGER NOT NULL DEFAULT 0,
    chunk_path TEXT NULL,
    chunk_size INTEGER NOT NULL DEFAULT 0,
    created_at TIMESTAMP NOT NULL DEFAULT now(),
    id BIGINT PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    upload_id VARCHAR(255) NULL
);

-- User: 用户账户
CREATE TABLE IF NOT EXISTS users (
    backup_codes TEXT NULL,
    bio TEXT NULL,
    date_joined TIMESTAMP NULL,
    email VARCHAR(254) UNIQUE NULL,
    id BIGINT PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    is_2fa_enabled BOOLEAN NOT NULL DEFAULT false,
    is_active BOOLEAN NOT NULL DEFAULT true,
    is_staff BOOLEAN NOT NULL DEFAULT false,
    is_superuser BOOLEAN NOT NULL DEFAULT false,
    last_login_at TIMESTAMP NULL,
    last_login_ip VARCHAR(45) NULL,
    locale VARCHAR(10) NOT NULL DEFAULT 'zh_CN',
    password TEXT NULL,
    profile_picture TEXT NULL,
    register_ip VARCHAR(45) NULL,
    total_storage BIGINT NOT NULL DEFAULT 1073741824,
    totp_secret TEXT NULL,
    used_storage BIGINT NOT NULL DEFAULT 0,
    username VARCHAR(150) UNIQUE NULL
);
CREATE INDEX IF NOT EXISTS idx_users_username ON users (username);
CREATE INDEX IF NOT EXISTS idx_users_email ON users (email);

-- RoleCapability: 角色-权限关联
CREATE TABLE IF NOT EXISTS role_capabilities (
    capability_id BIGINT NOT NULL REFERENCES capabilities(id) ON DELETE CASCADE,
    id BIGINT PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    role_id BIGINT NOT NULL REFERENCES roles(id) ON DELETE CASCADE
);

-- Notification: 通知
CREATE TABLE IF NOT EXISTS notifications (
    body TEXT NOT NULL,
    created_at TIMESTAMP NOT NULL DEFAULT now(),
    data TEXT NULL,
    id BIGINT PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    is_read BOOLEAN NOT NULL DEFAULT false,
    title VARCHAR(255) NOT NULL,
    type VARCHAR(50) NOT NULL,
    user_id BIGINT NOT NULL REFERENCES users(id) ON DELETE CASCADE
);

-- UserRole: 用户-角色关联
CREATE TABLE IF NOT EXISTS user_roles (
    id BIGINT PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    role_id BIGINT NOT NULL REFERENCES roles(id) ON DELETE CASCADE,
    user_id BIGINT NOT NULL REFERENCES users(id) ON DELETE CASCADE
);

-- UserSession: 用户登录会话
CREATE TABLE IF NOT EXISTS user_sessions (
    created_at TIMESTAMP NOT NULL DEFAULT now(),
    expires_at TIMESTAMP NULL,
    id BIGINT PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    ip_address VARCHAR(45) NULL,
    is_active BOOLEAN NOT NULL DEFAULT true,
    token TEXT NULL,
    user_agent TEXT NULL,
    user_id BIGINT NOT NULL REFERENCES users(id) ON DELETE CASCADE
);

-- Vault: 加密保险箱
CREATE TABLE IF NOT EXISTS vaults (
    created_at TIMESTAMP NOT NULL DEFAULT now(),
    description TEXT NULL,
    id BIGINT PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    name VARCHAR(255) NOT NULL,
    password_hash VARCHAR(128) NOT NULL DEFAULT '',
    updated_at TIMESTAMP NOT NULL DEFAULT now(),
    user_id BIGINT NOT NULL REFERENCES users(id) ON DELETE CASCADE
);

-- Folder: 文件夹
CREATE TABLE IF NOT EXISTS folders (
    created_at TIMESTAMP NOT NULL DEFAULT now(),
    id BIGINT PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    name VARCHAR(255) NOT NULL,
    parent_id BIGINT NULL REFERENCES folders(id) ON DELETE CASCADE,
    sort_order INTEGER NOT NULL DEFAULT 0,
    updated_at TIMESTAMP NOT NULL DEFAULT now(),
    user_id BIGINT NOT NULL REFERENCES users(id) ON DELETE CASCADE
);
CREATE INDEX IF NOT EXISTS idx_folders_user_id_parent_id ON folders (user_id, parent_id);

-- StorageQuota: 存储配额
CREATE TABLE IF NOT EXISTS storage_quotas (
    created_at TIMESTAMP NOT NULL DEFAULT now(),
    id BIGINT PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    total_bytes BIGINT NOT NULL DEFAULT 0,
    updated_at TIMESTAMP NOT NULL DEFAULT now(),
    used_bytes BIGINT NOT NULL DEFAULT 0,
    user_id BIGINT NOT NULL REFERENCES users(id) ON DELETE CASCADE
);

-- UploadTask: 文件上传任务
CREATE TABLE IF NOT EXISTS upload_tasks (
    chunk_size INTEGER NOT NULL DEFAULT 0,
    created_at TIMESTAMP NOT NULL DEFAULT now(),
    file_size BIGINT NOT NULL DEFAULT 0,
    filename VARCHAR(255) NULL,
    final_hash VARCHAR(64) NULL,
    first_chunk_hash VARCHAR(64) NULL,
    folder_id VARCHAR(50) NULL,
    id BIGINT PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    last_chunk_hash VARCHAR(64) NULL,
    mime_type VARCHAR(255) NULL,
    received_chunks INTEGER NOT NULL DEFAULT 0,
    status VARCHAR(20) NOT NULL DEFAULT 'pending',
    storage_path TEXT NULL,
    total_chunks INTEGER NOT NULL DEFAULT 0,
    updated_at TIMESTAMP NOT NULL DEFAULT now(),
    upload_id VARCHAR(255) NULL,
    user_id BIGINT NOT NULL REFERENCES users(id) ON DELETE CASCADE
);
CREATE INDEX IF NOT EXISTS idx_upload_tasks_status_updated_at ON upload_tasks (status, updated_at);

-- Team: 团队/群组
CREATE TABLE IF NOT EXISTS teams (
    created_at TIMESTAMP NOT NULL DEFAULT now(),
    description TEXT NULL,
    id BIGINT PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    name VARCHAR(255) NOT NULL,
    owner_id BIGINT NOT NULL REFERENCES users(id) ON DELETE CASCADE,
    updated_at TIMESTAMP NOT NULL DEFAULT now()
);

-- AuditLog: 审计日志
CREATE TABLE IF NOT EXISTS audit_logs (
    action VARCHAR(100) NOT NULL,
    created_at TIMESTAMP NOT NULL DEFAULT now(),
    detail TEXT NULL,
    id BIGINT PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    ip_address VARCHAR(45) NULL,
    resource TEXT NULL,
    user_id BIGINT NULL REFERENCES users(id) ON DELETE SET NULL
);

-- FileTag: 文件标签
CREATE TABLE IF NOT EXISTS file_tags (
    color VARCHAR(20) NULL,
    created_at TIMESTAMP NOT NULL DEFAULT now(),
    id BIGINT PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    name VARCHAR(100) NOT NULL,
    user_id BIGINT NOT NULL REFERENCES users(id) ON DELETE CASCADE
);

-- VaultItem: 保险箱条目
CREATE TABLE IF NOT EXISTS vault_items (
    content TEXT NULL,
    content_type VARCHAR(64) NOT NULL DEFAULT 'file',
    created_at TIMESTAMP NOT NULL DEFAULT now(),
    file_size BIGINT NOT NULL DEFAULT 0,
    filename VARCHAR(512) NOT NULL DEFAULT '',
    id BIGINT PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    mime_type VARCHAR(128) NOT NULL DEFAULT '',
    name VARCHAR(255) NOT NULL,
    updated_at TIMESTAMP NOT NULL DEFAULT now(),
    user_id BIGINT NOT NULL REFERENCES users(id) ON DELETE CASCADE,
    vault_id BIGINT NOT NULL REFERENCES vaults(id) ON DELETE CASCADE
);
CREATE INDEX IF NOT EXISTS idx_vault_items_vault_id_user_id ON vault_items (vault_id, user_id);

-- FileItem: 文件条目
CREATE TABLE IF NOT EXISTS file_items (
    created_at TIMESTAMP NOT NULL DEFAULT now(),
    deleted_at TIMESTAMP NULL,
    description TEXT NULL,
    download_count INTEGER NOT NULL DEFAULT 0,
    duration INTEGER NULL,
    file_hash VARCHAR(64) NULL,
    file_path TEXT NULL,
    file_size BIGINT NOT NULL DEFAULT 0,
    file_type VARCHAR(50) NOT NULL DEFAULT 'other',
    file_url TEXT NULL,
    filename VARCHAR(255) NULL,
    folder_id BIGINT NULL REFERENCES folders(id) ON DELETE SET NULL,
    height INTEGER NULL,
    id BIGINT PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    is_encrypted BOOLEAN NOT NULL DEFAULT false,
    is_favorite BOOLEAN NOT NULL DEFAULT false,
    is_folder BOOLEAN NOT NULL DEFAULT false,
    mime_type VARCHAR(255) NULL,
    original_filename VARCHAR(255) NULL,
    sort_order INTEGER NOT NULL DEFAULT 0,
    storage_bucket TEXT NULL,
    storage_driver VARCHAR(50) NOT NULL DEFAULT 'local',
    storage_key TEXT NULL,
    thumbnail_url TEXT NULL,
    updated_at TIMESTAMP NOT NULL DEFAULT now(),
    user_id BIGINT NOT NULL REFERENCES users(id) ON DELETE CASCADE,
    width INTEGER NULL
);
CREATE INDEX IF NOT EXISTS idx_file_items_user_id_deleted_at ON file_items (user_id, deleted_at);
CREATE INDEX IF NOT EXISTS idx_file_items_user_id_folder_id_deleted_at ON file_items (user_id, folder_id, deleted_at);
CREATE INDEX IF NOT EXISTS idx_file_items_user_id_file_type_deleted_at ON file_items (user_id, file_type, deleted_at);
CREATE INDEX IF NOT EXISTS idx_file_items_user_id_created_at_deleted_at ON file_items (user_id DESC, created_at DESC, deleted_at DESC);
CREATE INDEX IF NOT EXISTS idx_file_items_user_id_is_favorite_deleted_at ON file_items (user_id, is_favorite, deleted_at) WHERE is_favorite = true;

-- TeamFolder: 团队共享文件夹
CREATE TABLE IF NOT EXISTS team_folders (
    created_at TIMESTAMP NOT NULL DEFAULT now(),
    folder_id BIGINT NOT NULL REFERENCES folders(id) ON DELETE CASCADE,
    id BIGINT PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    permission VARCHAR(20) NOT NULL DEFAULT 'read',
    team_id BIGINT NOT NULL REFERENCES teams(id) ON DELETE CASCADE
);

-- TeamMember: 团队成员
CREATE TABLE IF NOT EXISTS team_members (
    created_at TIMESTAMP NOT NULL DEFAULT now(),
    id BIGINT PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    role VARCHAR(20) NOT NULL DEFAULT 'member',
    team_id BIGINT NOT NULL REFERENCES teams(id) ON DELETE CASCADE,
    user_id BIGINT NOT NULL REFERENCES users(id) ON DELETE CASCADE
);

-- FileShare: 用户间分享
CREATE TABLE IF NOT EXISTS file_shares (
    created_at TIMESTAMP NOT NULL DEFAULT now(),
    expires_at TIMESTAMP NULL,
    file_id BIGINT NOT NULL REFERENCES file_items(id) ON DELETE CASCADE,
    id BIGINT PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    owner_id BIGINT NOT NULL REFERENCES users(id) ON DELETE CASCADE,
    permission VARCHAR(20) NOT NULL DEFAULT 'view',
    shared_with BIGINT NOT NULL REFERENCES users(id) ON DELETE CASCADE
);

-- FileComment: 文件评论/批注
CREATE TABLE IF NOT EXISTS file_comments (
    content TEXT NOT NULL,
    created_at TIMESTAMP NOT NULL DEFAULT now(),
    file_id BIGINT NOT NULL REFERENCES file_items(id) ON DELETE CASCADE,
    id BIGINT PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    updated_at TIMESTAMP NOT NULL DEFAULT now(),
    user_id BIGINT NOT NULL REFERENCES users(id) ON DELETE CASCADE
);

-- FileVersion: 文件版本
CREATE TABLE IF NOT EXISTS file_versions (
    created_at TIMESTAMP NOT NULL DEFAULT now(),
    created_by BIGINT NULL REFERENCES users(id),
    file_hash VARCHAR(64) NULL,
    file_id BIGINT NOT NULL REFERENCES file_items(id) ON DELETE CASCADE,
    file_path TEXT NULL,
    file_size BIGINT NOT NULL DEFAULT 0,
    id BIGINT PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    version_num INTEGER NOT NULL DEFAULT 1
);

-- ShareLink: 分享链接
CREATE TABLE IF NOT EXISTS share_links (
    created_at TIMESTAMP NOT NULL DEFAULT now(),
    download_count INTEGER NOT NULL DEFAULT 0,
    expires_at TIMESTAMP NULL,
    file_id BIGINT NULL REFERENCES file_items(id) ON DELETE SET NULL,
    folder_id BIGINT NULL REFERENCES folders(id) ON DELETE SET NULL,
    id BIGINT PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    is_active BOOLEAN NOT NULL DEFAULT true,
    max_downloads INTEGER NOT NULL DEFAULT 0,
    password VARCHAR(128) NOT NULL DEFAULT '',
    permission VARCHAR(20) NOT NULL DEFAULT 'read',
    short_code VARCHAR(32) NOT NULL DEFAULT '',
    token VARCHAR(64) NOT NULL DEFAULT '',
    user_id BIGINT NOT NULL REFERENCES users(id) ON DELETE CASCADE,
    view_count INTEGER NOT NULL DEFAULT 0
);
CREATE INDEX IF NOT EXISTS idx_share_links_short_code ON share_links (short_code) WHERE short_code != '';
CREATE INDEX IF NOT EXISTS idx_share_links_user_id_created_at ON share_links (user_id DESC, created_at DESC);

-- FileTagAssignment: 文件-标签关联
CREATE TABLE IF NOT EXISTS file_tag_assignments (
    file_id BIGINT NOT NULL REFERENCES file_items(id) ON DELETE CASCADE,
    id BIGINT PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    tag_id BIGINT NOT NULL REFERENCES file_tags(id) ON DELETE CASCADE
);


-- DOWNGRADE
-- DROP schema_version (moved to end)
-- Capability
DROP TABLE IF EXISTS capabilities CASCADE;
-- FileFingerprint
DROP TABLE IF EXISTS file_fingerprints CASCADE;
-- LoginAttempt
DROP TABLE IF EXISTS login_attempts CASCADE;
-- Role
DROP TABLE IF EXISTS roles CASCADE;
-- SensitiveWord
DROP TABLE IF EXISTS sensitive_words CASCADE;
-- SystemSetting
DROP TABLE IF EXISTS system_settings CASCADE;
-- TokenBlacklist
DROP TABLE IF EXISTS token_blacklist CASCADE;
-- UploadChunk
DROP TABLE IF EXISTS upload_chunks CASCADE;
-- User
DROP TABLE IF EXISTS users CASCADE;
-- RoleCapability
DROP TABLE IF EXISTS role_capabilities CASCADE;
-- Notification
DROP TABLE IF EXISTS notifications CASCADE;
-- UserRole
DROP TABLE IF EXISTS user_roles CASCADE;
-- UserSession
DROP TABLE IF EXISTS user_sessions CASCADE;
-- Vault
DROP TABLE IF EXISTS vaults CASCADE;
-- Folder
DROP TABLE IF EXISTS folders CASCADE;
-- StorageQuota
DROP TABLE IF EXISTS storage_quotas CASCADE;
-- UploadTask
DROP TABLE IF EXISTS upload_tasks CASCADE;
-- Team
DROP TABLE IF EXISTS teams CASCADE;
-- AuditLog
DROP TABLE IF EXISTS audit_logs CASCADE;
-- FileTag
DROP TABLE IF EXISTS file_tags CASCADE;
-- VaultItem
DROP TABLE IF EXISTS vault_items CASCADE;
-- FileItem
DROP TABLE IF EXISTS file_items CASCADE;
-- TeamFolder
DROP TABLE IF EXISTS team_folders CASCADE;
-- TeamMember
DROP TABLE IF EXISTS team_members CASCADE;
-- FileShare
DROP TABLE IF EXISTS file_shares CASCADE;
-- FileComment
DROP TABLE IF EXISTS file_comments CASCADE;
-- FileVersion
DROP TABLE IF EXISTS file_versions CASCADE;
-- ShareLink
DROP TABLE IF EXISTS share_links CASCADE;
-- FileTagAssignment
DROP TABLE IF EXISTS file_tag_assignments CASCADE;

-- schema_version
DROP TABLE IF EXISTS schema_version CASCADE;
