-- UPGRADE
-- schema_version tracking table
CREATE TABLE IF NOT EXISTS schema_version (
    revision    VARCHAR(64) PRIMARY KEY,
    description TEXT NOT NULL DEFAULT '',
    applied_at  TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP
);

-- BlockStore: 4MB 块存储
CREATE TABLE IF NOT EXISTS block_store (
    created_at TIMESTAMP NOT NULL DEFAULT now(),
    hash VARCHAR(64) UNIQUE NOT NULL,
    id BIGINT PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    mime_type VARCHAR(100) NULL,
    ref_count INTEGER NOT NULL DEFAULT 1,
    size INTEGER NOT NULL DEFAULT 0,
    storage_path TEXT NOT NULL,
    updated_at TIMESTAMP NOT NULL DEFAULT now()
);

-- FileFingerprint: 文件去重指纹
CREATE TABLE IF NOT EXISTS file_fingerprints (
    created_at TIMESTAMP NOT NULL DEFAULT now(),
    file_size BIGINT NOT NULL DEFAULT 0,
    hash VARCHAR(64) UNIQUE NOT NULL,
    id BIGINT PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    mime_type VARCHAR(255) NULL,
    reference_count INTEGER NOT NULL DEFAULT 1,
    storage_path TEXT NULL,
    updated_at TIMESTAMP NOT NULL DEFAULT now()
);
CREATE INDEX IF NOT EXISTS idx_file_fingerprints_hash ON file_fingerprints (hash);

-- Role: 角色定义
CREATE TABLE IF NOT EXISTS roles (
    created_at TIMESTAMP NOT NULL DEFAULT now(),
    description TEXT NULL,
    id BIGINT PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    is_system BOOLEAN NOT NULL DEFAULT false,
    name VARCHAR(100) NOT NULL,
    slug VARCHAR(100) UNIQUE NOT NULL,
    updated_at TIMESTAMP NOT NULL DEFAULT now()
);

-- SensitiveWord: 敏感词
CREATE TABLE IF NOT EXISTS sensitive_words (
    created_at TIMESTAMP NOT NULL DEFAULT now(),
    id BIGINT PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    is_active BOOLEAN NOT NULL DEFAULT true,
    level INTEGER NOT NULL DEFAULT 1,
    replacement VARCHAR(255) NULL,
    updated_at TIMESTAMP NOT NULL DEFAULT now(),
    word VARCHAR(255) NOT NULL
);

-- SystemSetting: 系统设置
CREATE TABLE IF NOT EXISTS system_settings (
    created_at TIMESTAMP NOT NULL DEFAULT now(),
    description TEXT NULL,
    id BIGINT PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    is_public BOOLEAN NOT NULL DEFAULT false,
    setting_key VARCHAR(100) UNIQUE NOT NULL,
    setting_type VARCHAR(50) NULL,
    setting_value TEXT NOT NULL,
    updated_at TIMESTAMP NOT NULL DEFAULT now()
);

-- UploadChunk: 上传分片
CREATE TABLE IF NOT EXISTS upload_chunks (
    chunk_hash VARCHAR(64) NULL,
    chunk_index INTEGER NOT NULL DEFAULT 0,
    chunk_path TEXT NULL,
    chunk_size INTEGER NOT NULL DEFAULT 0,
    created_at TIMESTAMP NOT NULL DEFAULT now(),
    id BIGINT PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    upload_id VARCHAR(255) NULL
);

-- User: 用户账户
CREATE TABLE IF NOT EXISTS users (
    backup_codes TEXT NULL,
    bio TEXT NULL,
    date_joined TIMESTAMP NULL,
    email VARCHAR(254) UNIQUE NULL,
    id BIGINT PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    is_2fa_enabled BOOLEAN NOT NULL DEFAULT false,
    is_active BOOLEAN NOT NULL DEFAULT true,
    is_staff BOOLEAN NOT NULL DEFAULT false,
    is_superuser BOOLEAN NOT NULL DEFAULT false,
    last_login_at TIMESTAMP NULL,
    last_login_ip VARCHAR(45) NULL,
    locale VARCHAR(10) NOT NULL DEFAULT 'zh_CN',
    password TEXT NULL,
    profile_picture TEXT NULL,
    register_ip VARCHAR(45) NULL,
    total_storage BIGINT NOT NULL DEFAULT 10737418240,
    totp_secret TEXT NULL,
    used_storage BIGINT NOT NULL DEFAULT 0,
    username VARCHAR(150) UNIQUE NULL
);
CREATE INDEX IF NOT EXISTS idx_users_username ON users (username);
CREATE INDEX IF NOT EXISTS idx_users_email ON users (email);

-- FileBlock: 文件-块映射
CREATE TABLE IF NOT EXISTS file_blocks (
    block_hash VARCHAR(64) NOT NULL REFERENCES block_store(hash),
    block_index INTEGER NOT NULL,
    block_offset BIGINT NOT NULL DEFAULT 0,
    block_size INTEGER NOT NULL DEFAULT 0,
    created_at TIMESTAMP NOT NULL DEFAULT now(),
    file_hash VARCHAR(64) NOT NULL REFERENCES file_fingerprints(hash) ON DELETE CASCADE,
    id BIGINT PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY NOT NULL
);

-- UserSession: 用户登录会话
CREATE TABLE IF NOT EXISTS user_sessions (
    created_at TIMESTAMP NOT NULL DEFAULT now(),
    expires_at TIMESTAMP NULL,
    id BIGINT PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    ip_address VARCHAR(45) NULL,
    is_active BOOLEAN NOT NULL DEFAULT true,
    token TEXT NULL,
    user_agent TEXT NULL,
    user_id BIGINT NOT NULL REFERENCES users(id) ON DELETE CASCADE
);

-- Vault: 加密保险箱
CREATE TABLE IF NOT EXISTS vaults (
    created_at TIMESTAMP NOT NULL DEFAULT now(),
    description TEXT NULL,
    id BIGINT PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    name VARCHAR(255) NOT NULL,
    password_hash VARCHAR(128) NOT NULL DEFAULT '',
    updated_at TIMESTAMP NOT NULL DEFAULT now(),
    user_id BIGINT NOT NULL REFERENCES users(id) ON DELETE CASCADE
);

-- UploadTask: 上传任务
CREATE TABLE IF NOT EXISTS upload_tasks (
    chunk_size INTEGER NOT NULL DEFAULT 0,
    created_at TIMESTAMP NOT NULL DEFAULT now(),
    file_size BIGINT NOT NULL DEFAULT 0,
    filename VARCHAR(255) NULL,
    final_hash VARCHAR(64) NULL,
    first_chunk_hash VARCHAR(64) NULL,
    folder_id VARCHAR(50) NULL,
    id BIGINT PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    last_chunk_hash VARCHAR(64) NULL,
    mime_type VARCHAR(255) NULL,
    received_chunks INTEGER NOT NULL DEFAULT 0,
    status VARCHAR(20) NOT NULL DEFAULT 'pending',
    storage_path TEXT NULL,
    total_chunks INTEGER NOT NULL DEFAULT 0,
    updated_at TIMESTAMP NOT NULL DEFAULT now(),
    upload_id VARCHAR(255) NULL,
    user_id BIGINT NOT NULL REFERENCES users(id) ON DELETE CASCADE
);
CREATE INDEX IF NOT EXISTS idx_upload_tasks_status_updated_at ON upload_tasks (status, updated_at);

-- Webhook: Webhook
CREATE TABLE IF NOT EXISTS webhooks (
    created_at TIMESTAMP NOT NULL DEFAULT now(),
    events TEXT NOT NULL,
    id BIGINT PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    is_active BOOLEAN NOT NULL DEFAULT true,
    name VARCHAR(255) NOT NULL,
    updated_at TIMESTAMP NOT NULL DEFAULT now(),
    url VARCHAR(512) NOT NULL,
    user_id BIGINT NOT NULL REFERENCES users(id) ON DELETE CASCADE
);

-- AuditLog: 审计日志
CREATE TABLE IF NOT EXISTS audit_logs (
    action VARCHAR(100) NOT NULL,
    created_at TIMESTAMP NOT NULL DEFAULT now(),
    detail TEXT NULL,
    id BIGINT PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    ip_address VARCHAR(45) NULL,
    resource TEXT NULL,
    user_id BIGINT NULL REFERENCES users(id) ON DELETE SET NULL
);

-- Notification: 通知
CREATE TABLE IF NOT EXISTS notifications (
    body TEXT NOT NULL,
    created_at TIMESTAMP NOT NULL DEFAULT now(),
    data TEXT NULL,
    id BIGINT PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    is_read BOOLEAN NOT NULL DEFAULT false,
    title VARCHAR(255) NOT NULL,
    type VARCHAR(50) NOT NULL,
    user_id BIGINT NOT NULL REFERENCES users(id) ON DELETE CASCADE
);

-- Team: 团队
CREATE TABLE IF NOT EXISTS teams (
    created_at TIMESTAMP NOT NULL DEFAULT now(),
    description TEXT NULL,
    id BIGINT PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    name VARCHAR(255) NOT NULL,
    owner_id BIGINT NOT NULL REFERENCES users(id) ON DELETE CASCADE,
    updated_at TIMESTAMP NOT NULL DEFAULT now()
);

-- FileItem: 文件条目（is_folder=true 表示目录）
CREATE TABLE IF NOT EXISTS file_items (
    category VARCHAR(255) NULL,
    created_at TIMESTAMP NOT NULL DEFAULT now(),
    deleted_at TIMESTAMP NULL,
    description TEXT NULL,
    download_count INTEGER NOT NULL DEFAULT 0,
    duration INTEGER NULL,
    file_hash VARCHAR(64) NULL,
    file_path TEXT NULL,
    file_size BIGINT NOT NULL DEFAULT 0,
    file_type VARCHAR(50) NOT NULL DEFAULT 'other',
    file_url TEXT NULL,
    filename VARCHAR(255) NULL,
    folder_id BIGINT NULL REFERENCES file_items(id) ON DELETE SET NULL,
    height INTEGER NULL,
    id BIGINT PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    is_encrypted BOOLEAN NOT NULL DEFAULT false,
    is_favorite BOOLEAN NOT NULL DEFAULT false,
    is_folder BOOLEAN NOT NULL DEFAULT false,
    mime_type VARCHAR(255) NULL,
    original_filename VARCHAR(255) NULL,
    sort_order INTEGER NOT NULL DEFAULT 0,
    storage_bucket TEXT NULL,
    storage_driver VARCHAR(50) NOT NULL DEFAULT 'local',
    storage_key TEXT NULL,
    thumbnail_url TEXT NULL,
    updated_at TIMESTAMP NOT NULL DEFAULT now(),
    user_id BIGINT NOT NULL REFERENCES users(id) ON DELETE CASCADE,
    width INTEGER NULL
);
CREATE INDEX IF NOT EXISTS idx_file_items_user_id_deleted_at ON file_items (user_id, deleted_at);
CREATE INDEX IF NOT EXISTS idx_file_items_user_id_folder_id_deleted_at_is_folder ON file_items (user_id, folder_id, deleted_at, is_folder);
CREATE INDEX IF NOT EXISTS idx_file_items_user_id_file_type_deleted_at ON file_items (user_id, file_type, deleted_at);
CREATE INDEX IF NOT EXISTS idx_file_items_user_id_created_at_deleted_at ON file_items (user_id DESC, created_at DESC, deleted_at DESC);
CREATE INDEX IF NOT EXISTS idx_file_items_user_id_is_favorite_deleted_at ON file_items (user_id, is_favorite, deleted_at) WHERE is_favorite = true;

-- FileTag: 文件标签
CREATE TABLE IF NOT EXISTS file_tags (
    color VARCHAR(20) NULL,
    created_at TIMESTAMP NOT NULL DEFAULT now(),
    id BIGINT PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    name VARCHAR(100) NOT NULL,
    user_id BIGINT NOT NULL REFERENCES users(id) ON DELETE CASCADE
);

-- DownloadTask: 离线下载任务
CREATE TABLE IF NOT EXISTS download_tasks (
    created_at TIMESTAMP NOT NULL DEFAULT now(),
    filename VARCHAR(255) NULL,
    folder_id BIGINT NULL,
    id BIGINT PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    manual_retries INTEGER NOT NULL DEFAULT 0,
    progress INTEGER NOT NULL DEFAULT 0,
    retry_count INTEGER NOT NULL DEFAULT 0,
    status VARCHAR(20) NOT NULL DEFAULT 'pending',
    updated_at TIMESTAMP NOT NULL DEFAULT now(),
    url TEXT NOT NULL,
    user_id BIGINT NOT NULL REFERENCES users(id) ON DELETE CASCADE
);

-- VaultItem: 保险箱条目
CREATE TABLE IF NOT EXISTS vault_items (
    content_type VARCHAR(64) NOT NULL DEFAULT 'file',
    created_at TIMESTAMP NOT NULL DEFAULT now(),
    file_path TEXT NULL,
    file_size BIGINT NOT NULL DEFAULT 0,
    filename VARCHAR(512) NOT NULL DEFAULT '',
    id BIGINT PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    mime_type VARCHAR(128) NOT NULL DEFAULT '',
    name VARCHAR(255) NOT NULL,
    updated_at TIMESTAMP NOT NULL DEFAULT now(),
    user_id BIGINT NOT NULL REFERENCES users(id) ON DELETE CASCADE,
    vault_id BIGINT NOT NULL REFERENCES vaults(id) ON DELETE CASCADE
);
CREATE INDEX IF NOT EXISTS idx_vault_items_vault_id_user_id ON vault_items (vault_id, user_id);

-- WebhookEvent: Webhook 事件日志
CREATE TABLE IF NOT EXISTS webhook_events (
    created_at TIMESTAMP NOT NULL DEFAULT now(),
    event VARCHAR(50) NOT NULL,
    id BIGINT PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    payload TEXT NULL,
    response TEXT NULL,
    status VARCHAR(20) NOT NULL DEFAULT 'pending',
    webhook_id BIGINT NOT NULL REFERENCES webhooks(id) ON DELETE CASCADE
);

-- TeamMember: 团队成员
CREATE TABLE IF NOT EXISTS team_members (
    created_at TIMESTAMP NOT NULL DEFAULT now(),
    id BIGINT PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    role VARCHAR(20) NOT NULL DEFAULT 'member',
    team_id BIGINT NOT NULL REFERENCES teams(id) ON DELETE CASCADE,
    user_id BIGINT NOT NULL REFERENCES users(id) ON DELETE CASCADE
);

-- FileComment: 文件评论
CREATE TABLE IF NOT EXISTS file_comments (
    content TEXT NOT NULL,
    created_at TIMESTAMP NOT NULL DEFAULT now(),
    file_id BIGINT NOT NULL REFERENCES file_items(id) ON DELETE CASCADE,
    id BIGINT PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    updated_at TIMESTAMP NOT NULL DEFAULT now(),
    user_id BIGINT NOT NULL REFERENCES users(id) ON DELETE CASCADE
);

-- FileVersion: 文件版本
CREATE TABLE IF NOT EXISTS file_versions (
    created_at TIMESTAMP NOT NULL DEFAULT now(),
    created_by BIGINT NULL REFERENCES users(id),
    file_hash VARCHAR(64) NULL,
    file_id BIGINT NOT NULL REFERENCES file_items(id) ON DELETE CASCADE,
    file_path TEXT NULL,
    file_size BIGINT NOT NULL DEFAULT 0,
    id BIGINT PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    storage_driver VARCHAR(50) NOT NULL DEFAULT 'local',
    version_num INTEGER NOT NULL DEFAULT 1
);

-- TeamFolder: 团队文件夹
CREATE TABLE IF NOT EXISTS team_folders (
    created_at TIMESTAMP NOT NULL DEFAULT now(),
    folder_id BIGINT NOT NULL REFERENCES file_items(id) ON DELETE CASCADE,
    id BIGINT PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    permission VARCHAR(20) NOT NULL DEFAULT 'read',
    team_id BIGINT NOT NULL REFERENCES teams(id) ON DELETE CASCADE
);

-- ShareLink: 分享链接
CREATE TABLE IF NOT EXISTS share_links (
    created_at TIMESTAMP NOT NULL DEFAULT now(),
    download_count INTEGER NOT NULL DEFAULT 0,
    expires_at TIMESTAMP NULL,
    file_id BIGINT NULL REFERENCES file_items(id) ON DELETE SET NULL,
    folder_id BIGINT NULL REFERENCES file_items(id) ON DELETE SET NULL,
    id BIGINT PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    is_active BOOLEAN NOT NULL DEFAULT true,
    max_downloads INTEGER NOT NULL DEFAULT 0,
    password VARCHAR(128) NOT NULL DEFAULT '',
    permission VARCHAR(20) NOT NULL DEFAULT 'read',
    short_code VARCHAR(32) NOT NULL DEFAULT '',
    token VARCHAR(64) NOT NULL DEFAULT '',
    user_id BIGINT NOT NULL REFERENCES users(id) ON DELETE CASCADE,
    view_count INTEGER NOT NULL DEFAULT 0
);
CREATE INDEX IF NOT EXISTS idx_share_links_short_code ON share_links (short_code) WHERE short_code != '';
CREATE INDEX IF NOT EXISTS idx_share_links_user_id_created_at ON share_links (user_id DESC, created_at DESC);

-- TranscriptionTask: 转写任务
CREATE TABLE IF NOT EXISTS transcription_tasks (
    created_at TIMESTAMP NOT NULL DEFAULT now(),
    error_msg TEXT NULL,
    file_id BIGINT NOT NULL REFERENCES file_items(id) ON DELETE CASCADE,
    id BIGINT PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    progress INTEGER NOT NULL DEFAULT 0,
    result_url TEXT NULL,
    status VARCHAR(20) NOT NULL DEFAULT 'pending',
    updated_at TIMESTAMP NOT NULL DEFAULT now(),
    user_id BIGINT NOT NULL REFERENCES users(id) ON DELETE CASCADE
);

-- FileShare: 用户间分享
CREATE TABLE IF NOT EXISTS file_shares (
    created_at TIMESTAMP NOT NULL DEFAULT now(),
    expires_at TIMESTAMP NULL,
    file_id BIGINT NOT NULL REFERENCES file_items(id) ON DELETE CASCADE,
    id BIGINT PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    owner_id BIGINT NOT NULL REFERENCES users(id) ON DELETE CASCADE,
    permission VARCHAR(20) NOT NULL DEFAULT 'view',
    shared_with BIGINT NOT NULL REFERENCES users(id) ON DELETE CASCADE
);

-- FileTagAssignment: 文件-标签关联
CREATE TABLE IF NOT EXISTS file_tag_assignments (
    file_id BIGINT NOT NULL REFERENCES file_items(id) ON DELETE CASCADE,
    id BIGINT PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    tag_id BIGINT NOT NULL REFERENCES file_tags(id) ON DELETE CASCADE
);

-- ShareLinkItem: 批量分享的文件
CREATE TABLE IF NOT EXISTS share_link_items (
    created_at TIMESTAMP NOT NULL DEFAULT now(),
    file_id BIGINT NOT NULL REFERENCES file_items(id) ON DELETE CASCADE,
    id BIGINT PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    share_link_id BIGINT NOT NULL REFERENCES share_links(id) ON DELETE CASCADE
);


-- DOWNGRADE
-- DROP schema_version (moved to end)
-- BlockStore
DROP TABLE IF EXISTS block_store CASCADE;
-- FileFingerprint
DROP TABLE IF EXISTS file_fingerprints CASCADE;
-- Role
DROP TABLE IF EXISTS roles CASCADE;
-- SensitiveWord
DROP TABLE IF EXISTS sensitive_words CASCADE;
-- SystemSetting
DROP TABLE IF EXISTS system_settings CASCADE;
-- UploadChunk
DROP TABLE IF EXISTS upload_chunks CASCADE;
-- User
DROP TABLE IF EXISTS users CASCADE;
-- FileBlock
DROP TABLE IF EXISTS file_blocks CASCADE;
-- UserSession
DROP TABLE IF EXISTS user_sessions CASCADE;
-- Vault
DROP TABLE IF EXISTS vaults CASCADE;
-- UploadTask
DROP TABLE IF EXISTS upload_tasks CASCADE;
-- Webhook
DROP TABLE IF EXISTS webhooks CASCADE;
-- AuditLog
DROP TABLE IF EXISTS audit_logs CASCADE;
-- Notification
DROP TABLE IF EXISTS notifications CASCADE;
-- Team
DROP TABLE IF EXISTS teams CASCADE;
-- FileItem
DROP TABLE IF EXISTS file_items CASCADE;
-- FileTag
DROP TABLE IF EXISTS file_tags CASCADE;
-- DownloadTask
DROP TABLE IF EXISTS download_tasks CASCADE;
-- VaultItem
DROP TABLE IF EXISTS vault_items CASCADE;
-- WebhookEvent
DROP TABLE IF EXISTS webhook_events CASCADE;
-- TeamMember
DROP TABLE IF EXISTS team_members CASCADE;
-- FileComment
DROP TABLE IF EXISTS file_comments CASCADE;
-- FileVersion
DROP TABLE IF EXISTS file_versions CASCADE;
-- TeamFolder
DROP TABLE IF EXISTS team_folders CASCADE;
-- ShareLink
DROP TABLE IF EXISTS share_links CASCADE;
-- TranscriptionTask
DROP TABLE IF EXISTS transcription_tasks CASCADE;
-- FileShare
DROP TABLE IF EXISTS file_shares CASCADE;
-- FileTagAssignment
DROP TABLE IF EXISTS file_tag_assignments CASCADE;
-- ShareLinkItem
DROP TABLE IF EXISTS share_link_items CASCADE;

-- schema_version
DROP TABLE IF EXISTS schema_version CASCADE;
