package main

import (
	"fmt"
	"os"
	"sort"
	"strings"

	"gopkg.in/yaml.v3"
)

// ── YAML 模型定义结构 ──────────────────────────────

// SchemaDef 对应 config/models.yaml 顶层
type SchemaDef struct {
	Version int                 `yaml:"version"`
	Models  map[string]ModelDef `yaml:"models"`
}

// ModelDef 对应一个表定义
type ModelDef struct {
	Table       string              `yaml:"table"`
	Description string              `yaml:"description"`
	Columns     map[string]ColumnDef `yaml:"columns"`
	Indexes     []IndexDef          `yaml:"indexes"`
}

// ColumnDef 对应一个列定义
type ColumnDef struct {
	Type         string `yaml:"type"`
	Length       int    `yaml:"length"`
	PrimaryKey   bool   `yaml:"primary_key"`
	AutoIncrement bool  `yaml:"autoincrement"`
	Unique       bool   `yaml:"unique"`
	Null         bool   `yaml:"null"`
	Default      string `yaml:"default"`
	ForeignKey   string `yaml:"foreign_key"`
	OnDelete     string `yaml:"on_delete"`
}

// IndexDef 对应一个索引定义
type IndexDef struct {
	Columns []string `yaml:"columns"`
	Order   string   `yaml:"order"`
	Where   string   `yaml:"where"`
	Unique  bool     `yaml:"unique"`
}

// ── 解析 ──────────────────────────────────────────

// ParseSchema reads and parses config/models.yaml
func ParseSchema(path string) (*SchemaDef, error) {
	data, err := os.ReadFile(path)
	if err != nil {
		return nil, fmt.Errorf("读取 %s 失败: %w", path, err)
	}
	var s SchemaDef
	if err := yaml.Unmarshal(data, &s); err != nil {
		return nil, fmt.Errorf("解析 %s 失败: %w", path, err)
	}
	return &s, nil
}

// ── SQL 生成 ──────────────────────────────────────

// GenerateCreateSQL generates a CREATE TABLE statement from a model definition.
func (m ModelDef) GenerateCreateSQL() string {
	var b strings.Builder

	tableName := m.Table
	b.WriteString(fmt.Sprintf("CREATE TABLE IF NOT EXISTS %s (\n", tableName))

	// Sort columns for deterministic output
	var colNames []string
	for n := range m.Columns {
		colNames = append(colNames, n)
	}
	sort.Strings(colNames)

	var parts []string
	for _, name := range colNames {
		col := m.Columns[name]
		parts = append(parts, "    "+m.colToSQL(name, col))
	}
	b.WriteString(strings.Join(parts, ",\n"))
	b.WriteString("\n);\n")

	// Indexes
	for _, idx := range m.Indexes {
		b.WriteString(m.idxToSQL(tableName, idx))
	}

	return b.String()
}

// GenerateDropSQL generates a DROP TABLE statement.
func (m ModelDef) GenerateDropSQL() string {
	return fmt.Sprintf("DROP TABLE IF EXISTS %s CASCADE;\n", m.Table)
}

func (m ModelDef) colToSQL(name string, col ColumnDef) string {
	var b strings.Builder
	b.WriteString(name)

	switch col.Type {
	case "bigint":
		b.WriteString(" BIGINT")
	case "integer", "int":
		b.WriteString(" INTEGER")
	case "boolean", "bool":
		b.WriteString(" BOOLEAN")
	case "varchar":
		if col.Length > 0 {
			b.WriteString(fmt.Sprintf(" VARCHAR(%d)", col.Length))
		} else {
			b.WriteString(" VARCHAR(255)")
		}
	case "text":
		b.WriteString(" TEXT")
	case "timestamp":
		b.WriteString(" TIMESTAMP")
	case "float", "double":
		b.WriteString(" DOUBLE PRECISION")
	default:
		b.WriteString(" " + strings.ToUpper(col.Type))
	}

	if col.PrimaryKey {
		b.WriteString(" PRIMARY KEY")
		if col.AutoIncrement {
			b.WriteString(" GENERATED BY DEFAULT AS IDENTITY")
		}
	}

	if col.Unique && !col.PrimaryKey {
		b.WriteString(" UNIQUE")
	}

	// NOT NULL / NULL
	if col.PrimaryKey {
		b.WriteString(" NOT NULL")
	} else if col.Null {
		b.WriteString(" NULL")
	} else {
		b.WriteString(" NOT NULL")
	}

	// Default
	if col.Default != "" {
		b.WriteString(fmt.Sprintf(" DEFAULT %s", col.Default))
	}

	// Foreign key
	if col.ForeignKey != "" {
		ref := col.ForeignKey // format: "table(column)"
		refTable := ref
		refCol := "id"
		if paren := strings.Index(ref, "("); paren > 0 {
			refTable = ref[:paren]
			refCol = ref[paren+1 : len(ref)-1]
		}
		b.WriteString(fmt.Sprintf(" REFERENCES %s(%s)", refTable, refCol))
		if col.OnDelete != "" {
			b.WriteString(fmt.Sprintf(" ON DELETE %s", strings.ToUpper(col.OnDelete)))
		}
	}

	return b.String()
}

func (m ModelDef) idxToSQL(table string, idx IndexDef) string {
	cols := make([]string, len(idx.Columns))
	for i, c := range idx.Columns {
		order := ""
		if idx.Order == "desc" {
			order = " DESC"
		}
		cols[i] = c + order
	}

	colList := strings.Join(cols, ", ")
	idxName := fmt.Sprintf("idx_%s_%s", table, strings.Join(idx.Columns, "_"))

	var b strings.Builder
	if idx.Unique {
		b.WriteString(fmt.Sprintf("CREATE UNIQUE INDEX IF NOT EXISTS %s ON %s (%s)", idxName, table, colList))
	} else {
		b.WriteString(fmt.Sprintf("CREATE INDEX IF NOT EXISTS %s ON %s (%s)", idxName, table, colList))
	}
	if idx.Where != "" {
		b.WriteString(fmt.Sprintf(" WHERE %s", idx.Where))
	}
	b.WriteString(";\n")
	return b.String()
}

// ── 版本.ini 管理 ──────────────────────────────────

func readVersionINI(path string) (int, error) {
	data, err := os.ReadFile(path)
	if err != nil {
		if os.IsNotExist(err) {
			return 0, nil
		}
		return 0, err
	}
	// Simple INI parser: look for "current = <number>"
	for _, line := range strings.Split(string(data), "\n") {
		line = strings.TrimSpace(line)
		if strings.HasPrefix(line, "current") || strings.HasPrefix(line, "current") {
			parts := strings.SplitN(line, "=", 2)
			if len(parts) == 2 {
				var v int
				if _, err := fmt.Sscanf(strings.TrimSpace(parts[1]), "%d", &v); err == nil {
					return v, nil
				}
			}
		}
	}
	return 0, nil
}

func writeVersionINI(path string, version int) error {
	content := fmt.Sprintf(`[schema]
# 当前数据库 schema 版本
# 由 `+"`stora-cli migrate up/down`"+` 自动维护
current = %d
`, version)
	return os.WriteFile(path, []byte(content), 0644)
}
